namespace WhatTheHelmRuntime
{
    partial class TrimControl
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Mitov.BasicLab.ControlBackground controlBackground3 = new Mitov.BasicLab.ControlBackground();
            Mitov.BasicLab.RectControlBorder rectControlBorder3 = new Mitov.BasicLab.RectControlBorder();
            Mitov.BasicLab.ControlInnerBevel controlInnerBevel3 = new Mitov.BasicLab.ControlInnerBevel();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TrimControl));
            Mitov.BasicLab.ElementSize elementSize47 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ControlBevel controlBevel3 = new Mitov.BasicLab.ControlBevel();
            Mitov.BasicLab.ElementSize elementSize48 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize49 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize50 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.VerticalCaption verticalCaption3 = new Mitov.BasicLab.VerticalCaption();
            Mitov.BasicLab.ControlFont controlFont7 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush17 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend17 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends17 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape17 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient17 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor17 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint17 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors17 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints17 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch17 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors17 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen7 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush18 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend18 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends18 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape18 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient18 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor18 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint18 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors18 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints18 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch18 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors18 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound7 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle7 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash7 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize51 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets5 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize9 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize10 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.InstrumentLab.Glass glass3 = new Mitov.InstrumentLab.Glass();
            Mitov.InstrumentLab.OptionalLinearGaugeHand optionalLinearGaugeHand3 = new Mitov.InstrumentLab.OptionalLinearGaugeHand();
            Mitov.InstrumentLab.HandAnimation handAnimation3 = new Mitov.InstrumentLab.HandAnimation();
            Mitov.BasicLab.ElementSize elementSize52 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ElementShadow elementShadow3 = new Mitov.InstrumentLab.ElementShadow();
            Mitov.BasicLab.ElementSize elementSize53 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize54 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize55 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize56 = new Mitov.BasicLab.ElementSize();
            OpenWire.Proxy.SinkPin sinkPin3 = new OpenWire.Proxy.SinkPin();
            Mitov.InstrumentLab.LinearGaugeRail linearGaugeRail3 = new Mitov.InstrumentLab.LinearGaugeRail();
            Mitov.BasicLab.ElementSize elementSize57 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets6 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize11 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize12 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementSize elementSize58 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.AnalogGaugeScaleRanges analogGaugeScaleRanges3 = new Mitov.InstrumentLab.AnalogGaugeScaleRanges();
            Mitov.BasicLab.ElementSize elementSize59 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize60 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.Rotation rotation3 = new Mitov.InstrumentLab.Rotation();
            Mitov.InstrumentLab.ReversibleGaugeScale reversibleGaugeScale3 = new Mitov.InstrumentLab.ReversibleGaugeScale();
            Mitov.InstrumentLab.InstrumentMajorTicks instrumentMajorTicks3 = new Mitov.InstrumentLab.InstrumentMajorTicks();
            Mitov.BasicLab.GPBrush gpBrush19 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend19 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends19 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape19 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient19 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor19 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint19 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors19 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints19 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch19 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors19 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText5 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont8 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush20 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend20 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends20 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape20 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient20 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor20 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint20 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors20 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints20 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch20 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors20 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen8 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush21 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend21 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends21 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape21 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient21 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor21 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint21 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors21 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints21 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch21 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors21 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound8 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle8 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash8 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize61 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize62 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize63 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick5 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty5 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick6 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty6 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.BasicLab.ElementSize elementSize64 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentLabeledTicks instrumentLabeledTicks3 = new Mitov.InstrumentLab.InstrumentLabeledTicks();
            Mitov.BasicLab.GPBrush gpBrush22 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend22 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends22 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape22 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient22 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor22 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint22 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors22 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints22 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch22 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors22 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText6 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont9 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush23 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend23 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends23 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape23 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient23 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor23 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint23 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors23 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints23 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch23 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors23 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen9 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush24 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend24 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends24 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape24 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient24 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor24 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint24 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors24 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints24 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch24 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors24 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound9 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle9 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash9 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize65 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize66 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize67 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize68 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize69 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ScalePrecision scalePrecision3 = new Mitov.InstrumentLab.ScalePrecision();
            Mitov.BasicLab.ControlBackground controlBackground4 = new Mitov.BasicLab.ControlBackground();
            Mitov.BasicLab.RectControlBorder rectControlBorder4 = new Mitov.BasicLab.RectControlBorder();
            Mitov.BasicLab.ControlInnerBevel controlInnerBevel4 = new Mitov.BasicLab.ControlInnerBevel();
            Mitov.BasicLab.ElementSize elementSize70 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ControlBevel controlBevel4 = new Mitov.BasicLab.ControlBevel();
            Mitov.BasicLab.ElementSize elementSize71 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize72 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize73 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.VerticalCaption verticalCaption4 = new Mitov.BasicLab.VerticalCaption();
            Mitov.BasicLab.ControlFont controlFont10 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush25 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend25 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends25 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape25 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient25 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor25 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint25 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors25 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints25 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch25 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors25 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen10 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush26 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend26 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends26 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape26 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient26 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor26 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint26 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors26 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints26 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch26 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors26 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound10 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle10 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash10 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize74 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets7 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize13 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize14 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.InstrumentLab.Glass glass4 = new Mitov.InstrumentLab.Glass();
            Mitov.InstrumentLab.OptionalLinearGaugeHand optionalLinearGaugeHand4 = new Mitov.InstrumentLab.OptionalLinearGaugeHand();
            Mitov.InstrumentLab.HandAnimation handAnimation4 = new Mitov.InstrumentLab.HandAnimation();
            Mitov.BasicLab.ElementSize elementSize75 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ElementShadow elementShadow4 = new Mitov.InstrumentLab.ElementShadow();
            Mitov.BasicLab.ElementSize elementSize76 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize77 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize78 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize79 = new Mitov.BasicLab.ElementSize();
            OpenWire.Proxy.SinkPin sinkPin4 = new OpenWire.Proxy.SinkPin();
            Mitov.InstrumentLab.LinearGaugeRail linearGaugeRail4 = new Mitov.InstrumentLab.LinearGaugeRail();
            Mitov.BasicLab.ElementSize elementSize80 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets8 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize15 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize16 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementSize elementSize81 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.AnalogGaugeScaleRanges analogGaugeScaleRanges4 = new Mitov.InstrumentLab.AnalogGaugeScaleRanges();
            Mitov.BasicLab.ElementSize elementSize82 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize83 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.Rotation rotation4 = new Mitov.InstrumentLab.Rotation();
            Mitov.InstrumentLab.ReversibleGaugeScale reversibleGaugeScale4 = new Mitov.InstrumentLab.ReversibleGaugeScale();
            Mitov.InstrumentLab.InstrumentMajorTicks instrumentMajorTicks4 = new Mitov.InstrumentLab.InstrumentMajorTicks();
            Mitov.BasicLab.GPBrush gpBrush27 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend27 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends27 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape27 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient27 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor27 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint27 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors27 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints27 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch27 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors27 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText7 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont11 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush28 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend28 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends28 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape28 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient28 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor28 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint28 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors28 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints28 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch28 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors28 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen11 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush29 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend29 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends29 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape29 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient29 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor29 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint29 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors29 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints29 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch29 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors29 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound11 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle11 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash11 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize84 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize85 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize86 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick7 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty7 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick8 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty8 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.BasicLab.ElementSize elementSize87 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentLabeledTicks instrumentLabeledTicks4 = new Mitov.InstrumentLab.InstrumentLabeledTicks();
            Mitov.BasicLab.GPBrush gpBrush30 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend30 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends30 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape30 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient30 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor30 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint30 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors30 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints30 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch30 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors30 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText8 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont12 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush31 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend31 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends31 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape31 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient31 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor31 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint31 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors31 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints31 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch31 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors31 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen12 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush32 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend32 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends32 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape32 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient32 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor32 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint32 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors32 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints32 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch32 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors32 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound12 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle12 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash12 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize88 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize89 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize90 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize91 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize92 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ScalePrecision scalePrecision4 = new Mitov.InstrumentLab.ScalePrecision();
            this.gaugeStbdTrim = new Mitov.InstrumentLab.LinearGauge(this.components);
            this.gaugePortTrim = new Mitov.InstrumentLab.LinearGauge(this.components);
            this.label36 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.label4 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.btnConfigNmea2000 = new System.Windows.Forms.Button();
            this.btnPortBowDown = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.btnPortBowUp = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.btnStbdBowDown = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.btnStbdBowUp = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.btnSync = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.gaugeStbdTrim)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gaugePortTrim)).BeginInit();
            this.SuspendLayout();
            // 
            // gaugeStbdTrim
            // 
            controlBackground3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.gaugeStbdTrim.Background = controlBackground3;
            controlInnerBevel3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlInnerBevel3.InternalData")));
            elementSize47.Value = 0.05F;
            controlInnerBevel3.Width = elementSize47;
            rectControlBorder3.BevelInner = controlInnerBevel3;
            elementSize48.Value = 0.05F;
            controlBevel3.Width = elementSize48;
            rectControlBorder3.BevelOuter = controlBevel3;
            rectControlBorder3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            elementSize49.Value = 0.2F;
            rectControlBorder3.CornerRadius = elementSize49;
            rectControlBorder3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("rectControlBorder3.InternalData")));
            elementSize50.Value = 0F;
            rectControlBorder3.Width = elementSize50;
            this.gaugeStbdTrim.Border = rectControlBorder3;
            verticalCaption3.Angle = 0F;
            gpBlend17.Blends = gpBlends17;
            gpBlendShape17.Focus = 0.5F;
            gpBlendShape17.Scale = 1F;
            gpBlend17.Shape = gpBlendShape17;
            gpBrush17.Blend = gpBlend17;
            gpBrush17.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor17.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint17.X = 0F;
            gpCenterPoint17.Y = 0F;
            gpCenterColor17.Point = gpCenterPoint17;
            gpGradient17.CenterColor = gpCenterColor17;
            gpGradient17.Colors = gpColors17;
            gpGradient17.Path = gpPoints17;
            gpBrush17.Gradient = gpGradient17;
            gpHatch17.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch17.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush17.Hatch = gpHatch17;
            gpBrush17.InterpolationColors = gpInterpolationColors17;
            controlFont7.Brush = gpBrush17;
            controlFont7.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont7.InternalData")));
            gpBlend18.Blends = gpBlends18;
            gpBlendShape18.Focus = 0.5F;
            gpBlendShape18.Scale = 1F;
            gpBlend18.Shape = gpBlendShape18;
            gpBrush18.Blend = gpBlend18;
            gpBrush18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint18.X = 0F;
            gpCenterPoint18.Y = 0F;
            gpCenterColor18.Point = gpCenterPoint18;
            gpGradient18.CenterColor = gpCenterColor18;
            gpGradient18.Colors = gpColors18;
            gpGradient18.Path = gpPoints18;
            gpBrush18.Gradient = gpGradient18;
            gpHatch18.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch18.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush18.Hatch = gpHatch18;
            gpBrush18.InterpolationColors = gpInterpolationColors18;
            gpOptionalMultiPen7.Brush = gpBrush18;
            gpOptionalMultiPen7.Compound = gpPenCompound7;
            gpDashStyle7.CustomDash = gpCustomDash7;
            gpDashStyle7.Offset = 0F;
            gpOptionalMultiPen7.DashStyle = gpDashStyle7;
            gpOptionalMultiPen7.Enabled = false;
            gpOptionalMultiPen7.MiterLimit = 0F;
            gpOptionalMultiPen7.Width = 1F;
            controlFont7.Pen = gpOptionalMultiPen7;
            elementSize51.Value = 0.25F;
            controlFont7.Size = elementSize51;
            verticalCaption3.Font = controlFont7;
            elementOffsetSize9.Value = 0.8F;
            elementOffsets5.X = elementOffsetSize9;
            elementOffsetSize10.Value = 0F;
            elementOffsets5.Y = elementOffsetSize10;
            verticalCaption3.Position = elementOffsets5;
            this.gaugeStbdTrim.Caption = verticalCaption3;
            this.gaugeStbdTrim.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.gaugeStbdTrim.Curved = false;
            glass3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            glass3.Visible = false;
            this.gaugeStbdTrim.Glass = glass3;
            handAnimation3.Acceleration = 0.015F;
            handAnimation3.Resistance = 0.16F;
            optionalLinearGaugeHand3.Animation = handAnimation3;
            optionalLinearGaugeHand3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            elementSize52.Value = 0.33F;
            optionalLinearGaugeHand3.Length = elementSize52;
            optionalLinearGaugeHand3.Shadow = elementShadow3;
            elementSize53.Value = 0.15F;
            optionalLinearGaugeHand3.TailIndentSize = elementSize53;
            elementSize54.Value = 0.65F;
            optionalLinearGaugeHand3.TipLength = elementSize54;
            elementSize55.Value = 0.2F;
            optionalLinearGaugeHand3.TipWidth = elementSize55;
            elementSize56.Value = 0.03F;
            optionalLinearGaugeHand3.Width = elementSize56;
            this.gaugeStbdTrim.Hand = optionalLinearGaugeHand3;
            this.gaugeStbdTrim.InputPin = sinkPin3;
            this.gaugeStbdTrim.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("gaugeStbdTrim.InternalData")));
            this.gaugeStbdTrim.Location = new System.Drawing.Point(408, 47);
            this.gaugeStbdTrim.Max = 0D;
            this.gaugeStbdTrim.Min = -100D;
            this.gaugeStbdTrim.Name = "gaugeStbdTrim";
            elementSize57.Value = 0.9F;
            linearGaugeRail3.Length = elementSize57;
            elementOffsetSize11.Value = 0.1F;
            elementOffsets6.X = elementOffsetSize11;
            elementOffsetSize12.Value = 0F;
            elementOffsets6.Y = elementOffsetSize12;
            linearGaugeRail3.Position = elementOffsets6;
            elementSize58.Value = 0.08F;
            linearGaugeRail3.Width = elementSize58;
            this.gaugeStbdTrim.Rail = linearGaugeRail3;
            analogGaugeScaleRanges3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            elementSize59.Value = 0.2F;
            analogGaugeScaleRanges3.Position = elementSize59;
            elementSize60.Value = 0.05F;
            analogGaugeScaleRanges3.Width = elementSize60;
            this.gaugeStbdTrim.Ranges = analogGaugeScaleRanges3;
            rotation3.Angle = 0F;
            rotation3.Width = 0.7F;
            this.gaugeStbdTrim.Rotation = rotation3;
            gpBlend19.Blends = gpBlends19;
            gpBlendShape19.Focus = 0.5F;
            gpBlendShape19.Scale = 1F;
            gpBlend19.Shape = gpBlendShape19;
            gpBrush19.Blend = gpBlend19;
            gpBrush19.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor19.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint19.X = 0F;
            gpCenterPoint19.Y = 0F;
            gpCenterColor19.Point = gpCenterPoint19;
            gpGradient19.CenterColor = gpCenterColor19;
            gpGradient19.Colors = gpColors19;
            gpGradient19.Path = gpPoints19;
            gpBrush19.Gradient = gpGradient19;
            gpHatch19.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch19.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush19.Hatch = gpHatch19;
            gpBrush19.InterpolationColors = gpInterpolationColors19;
            instrumentMajorTicks3.Brush = gpBrush19;
            instrumentMajorTicks3.Count = ((uint)(5u));
            instrumentTicksText5.Angle = 0F;
            gpBlend20.Blends = gpBlends20;
            gpBlendShape20.Focus = 0.5F;
            gpBlendShape20.Scale = 1F;
            gpBlend20.Shape = gpBlendShape20;
            gpBrush20.Blend = gpBlend20;
            gpBrush20.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor20.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint20.X = 0F;
            gpCenterPoint20.Y = 0F;
            gpCenterColor20.Point = gpCenterPoint20;
            gpGradient20.CenterColor = gpCenterColor20;
            gpGradient20.Colors = gpColors20;
            gpGradient20.Path = gpPoints20;
            gpBrush20.Gradient = gpGradient20;
            gpHatch20.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch20.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush20.Hatch = gpHatch20;
            gpBrush20.InterpolationColors = gpInterpolationColors20;
            controlFont8.Brush = gpBrush20;
            controlFont8.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont8.InternalData")));
            gpBlend21.Blends = gpBlends21;
            gpBlendShape21.Focus = 0.5F;
            gpBlendShape21.Scale = 1F;
            gpBlend21.Shape = gpBlendShape21;
            gpBrush21.Blend = gpBlend21;
            gpBrush21.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor21.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint21.X = 0F;
            gpCenterPoint21.Y = 0F;
            gpCenterColor21.Point = gpCenterPoint21;
            gpGradient21.CenterColor = gpCenterColor21;
            gpGradient21.Colors = gpColors21;
            gpGradient21.Path = gpPoints21;
            gpBrush21.Gradient = gpGradient21;
            gpHatch21.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch21.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush21.Hatch = gpHatch21;
            gpBrush21.InterpolationColors = gpInterpolationColors21;
            gpOptionalMultiPen8.Brush = gpBrush21;
            gpOptionalMultiPen8.Compound = gpPenCompound8;
            gpDashStyle8.CustomDash = gpCustomDash8;
            gpDashStyle8.Offset = 0F;
            gpOptionalMultiPen8.DashStyle = gpDashStyle8;
            gpOptionalMultiPen8.Enabled = false;
            gpOptionalMultiPen8.MiterLimit = 0F;
            gpOptionalMultiPen8.Width = 1F;
            controlFont8.Pen = gpOptionalMultiPen8;
            elementSize61.Value = 0.09F;
            controlFont8.Size = elementSize61;
            instrumentTicksText5.Font = controlFont8;
            elementSize62.Value = 0.5F;
            instrumentTicksText5.Position = elementSize62;
            instrumentTicksText5.Visible = true;
            instrumentMajorTicks3.Labels = instrumentTicksText5;
            elementSize63.Value = 0.25F;
            instrumentMajorTicks3.Length = elementSize63;
            optionalInstrumentProperty5.Visible = true;
            instrumentEndTick5.TickLabel = optionalInstrumentProperty5;
            instrumentEndTick5.Visible = true;
            instrumentMajorTicks3.MaxTick = instrumentEndTick5;
            optionalInstrumentProperty6.Visible = true;
            instrumentEndTick6.TickLabel = optionalInstrumentProperty6;
            instrumentEndTick6.Visible = true;
            instrumentMajorTicks3.MinTick = instrumentEndTick6;
            elementSize64.Value = 0.01F;
            instrumentMajorTicks3.Thickness = elementSize64;
            instrumentMajorTicks3.Visible = true;
            reversibleGaugeScale3.MajorTicks = instrumentMajorTicks3;
            gpBlend22.Blends = gpBlends22;
            gpBlendShape22.Focus = 0.5F;
            gpBlendShape22.Scale = 1F;
            gpBlend22.Shape = gpBlendShape22;
            gpBrush22.Blend = gpBlend22;
            gpBrush22.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor22.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint22.X = 0F;
            gpCenterPoint22.Y = 0F;
            gpCenterColor22.Point = gpCenterPoint22;
            gpGradient22.CenterColor = gpCenterColor22;
            gpGradient22.Colors = gpColors22;
            gpGradient22.Path = gpPoints22;
            gpBrush22.Gradient = gpGradient22;
            gpHatch22.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch22.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush22.Hatch = gpHatch22;
            gpBrush22.InterpolationColors = gpInterpolationColors22;
            instrumentLabeledTicks3.Brush = gpBrush22;
            instrumentLabeledTicks3.Count = ((uint)(3u));
            instrumentTicksText6.Angle = 0F;
            gpBlend23.Blends = gpBlends23;
            gpBlendShape23.Focus = 0.5F;
            gpBlendShape23.Scale = 1F;
            gpBlend23.Shape = gpBlendShape23;
            gpBrush23.Blend = gpBlend23;
            gpBrush23.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor23.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint23.X = 0F;
            gpCenterPoint23.Y = 0F;
            gpCenterColor23.Point = gpCenterPoint23;
            gpGradient23.CenterColor = gpCenterColor23;
            gpGradient23.Colors = gpColors23;
            gpGradient23.Path = gpPoints23;
            gpBrush23.Gradient = gpGradient23;
            gpHatch23.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch23.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush23.Hatch = gpHatch23;
            gpBrush23.InterpolationColors = gpInterpolationColors23;
            controlFont9.Brush = gpBrush23;
            controlFont9.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont9.InternalData")));
            gpBlend24.Blends = gpBlends24;
            gpBlendShape24.Focus = 0.5F;
            gpBlendShape24.Scale = 1F;
            gpBlend24.Shape = gpBlendShape24;
            gpBrush24.Blend = gpBlend24;
            gpBrush24.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor24.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint24.X = 0F;
            gpCenterPoint24.Y = 0F;
            gpCenterColor24.Point = gpCenterPoint24;
            gpGradient24.CenterColor = gpCenterColor24;
            gpGradient24.Colors = gpColors24;
            gpGradient24.Path = gpPoints24;
            gpBrush24.Gradient = gpGradient24;
            gpHatch24.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch24.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush24.Hatch = gpHatch24;
            gpBrush24.InterpolationColors = gpInterpolationColors24;
            gpOptionalMultiPen9.Brush = gpBrush24;
            gpOptionalMultiPen9.Compound = gpPenCompound9;
            gpDashStyle9.CustomDash = gpCustomDash9;
            gpDashStyle9.Offset = 0F;
            gpOptionalMultiPen9.DashStyle = gpDashStyle9;
            gpOptionalMultiPen9.Enabled = false;
            gpOptionalMultiPen9.MiterLimit = 0F;
            gpOptionalMultiPen9.Width = 1F;
            controlFont9.Pen = gpOptionalMultiPen9;
            elementSize65.Value = 0.065F;
            controlFont9.Size = elementSize65;
            instrumentTicksText6.Font = controlFont9;
            elementSize66.Value = 0.45F;
            instrumentTicksText6.Position = elementSize66;
            instrumentTicksText6.Visible = false;
            instrumentLabeledTicks3.Labels = instrumentTicksText6;
            elementSize67.Value = 0.15F;
            instrumentLabeledTicks3.Length = elementSize67;
            elementSize68.Value = 0.005F;
            instrumentLabeledTicks3.Thickness = elementSize68;
            instrumentLabeledTicks3.Visible = true;
            reversibleGaugeScale3.MinorTicks = instrumentLabeledTicks3;
            elementSize69.Value = 0.25F;
            reversibleGaugeScale3.Position = elementSize69;
            scalePrecision3.FixedPrecision = false;
            scalePrecision3.NumberDigits = ((uint)(2u));
            reversibleGaugeScale3.Precision = scalePrecision3;
            this.gaugeStbdTrim.Scale = reversibleGaugeScale3;
            this.gaugeStbdTrim.Size = new System.Drawing.Size(158, 424);
            this.gaugeStbdTrim.TabIndex = 0;
            this.gaugeStbdTrim.TabStop = false;
            this.gaugeStbdTrim.Text = "linearGauge1";
            this.gaugeStbdTrim.Value = 0D;
            // 
            // gaugePortTrim
            // 
            controlBackground4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.gaugePortTrim.Background = controlBackground4;
            controlInnerBevel4.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlInnerBevel4.InternalData")));
            elementSize70.Value = 0.05F;
            controlInnerBevel4.Width = elementSize70;
            rectControlBorder4.BevelInner = controlInnerBevel4;
            elementSize71.Value = 0.05F;
            controlBevel4.Width = elementSize71;
            rectControlBorder4.BevelOuter = controlBevel4;
            rectControlBorder4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            elementSize72.Value = 0.2F;
            rectControlBorder4.CornerRadius = elementSize72;
            rectControlBorder4.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("rectControlBorder4.InternalData")));
            elementSize73.Value = 0F;
            rectControlBorder4.Width = elementSize73;
            this.gaugePortTrim.Border = rectControlBorder4;
            verticalCaption4.Angle = 0F;
            gpBlend25.Blends = gpBlends25;
            gpBlendShape25.Focus = 0.5F;
            gpBlendShape25.Scale = 1F;
            gpBlend25.Shape = gpBlendShape25;
            gpBrush25.Blend = gpBlend25;
            gpBrush25.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor25.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint25.X = 0F;
            gpCenterPoint25.Y = 0F;
            gpCenterColor25.Point = gpCenterPoint25;
            gpGradient25.CenterColor = gpCenterColor25;
            gpGradient25.Colors = gpColors25;
            gpGradient25.Path = gpPoints25;
            gpBrush25.Gradient = gpGradient25;
            gpHatch25.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch25.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush25.Hatch = gpHatch25;
            gpBrush25.InterpolationColors = gpInterpolationColors25;
            controlFont10.Brush = gpBrush25;
            controlFont10.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont10.InternalData")));
            gpBlend26.Blends = gpBlends26;
            gpBlendShape26.Focus = 0.5F;
            gpBlendShape26.Scale = 1F;
            gpBlend26.Shape = gpBlendShape26;
            gpBrush26.Blend = gpBlend26;
            gpBrush26.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor26.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint26.X = 0F;
            gpCenterPoint26.Y = 0F;
            gpCenterColor26.Point = gpCenterPoint26;
            gpGradient26.CenterColor = gpCenterColor26;
            gpGradient26.Colors = gpColors26;
            gpGradient26.Path = gpPoints26;
            gpBrush26.Gradient = gpGradient26;
            gpHatch26.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch26.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush26.Hatch = gpHatch26;
            gpBrush26.InterpolationColors = gpInterpolationColors26;
            gpOptionalMultiPen10.Brush = gpBrush26;
            gpOptionalMultiPen10.Compound = gpPenCompound10;
            gpDashStyle10.CustomDash = gpCustomDash10;
            gpDashStyle10.Offset = 0F;
            gpOptionalMultiPen10.DashStyle = gpDashStyle10;
            gpOptionalMultiPen10.Enabled = false;
            gpOptionalMultiPen10.MiterLimit = 0F;
            gpOptionalMultiPen10.Width = 1F;
            controlFont10.Pen = gpOptionalMultiPen10;
            elementSize74.Value = 0.25F;
            controlFont10.Size = elementSize74;
            verticalCaption4.Font = controlFont10;
            elementOffsetSize13.Value = 0.8F;
            elementOffsets7.X = elementOffsetSize13;
            elementOffsetSize14.Value = 0F;
            elementOffsets7.Y = elementOffsetSize14;
            verticalCaption4.Position = elementOffsets7;
            this.gaugePortTrim.Caption = verticalCaption4;
            this.gaugePortTrim.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.gaugePortTrim.Curved = false;
            glass4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            glass4.Visible = false;
            this.gaugePortTrim.Glass = glass4;
            handAnimation4.Acceleration = 0.015F;
            handAnimation4.Resistance = 0.16F;
            optionalLinearGaugeHand4.Animation = handAnimation4;
            optionalLinearGaugeHand4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            elementSize75.Value = 0.33F;
            optionalLinearGaugeHand4.Length = elementSize75;
            optionalLinearGaugeHand4.Shadow = elementShadow4;
            elementSize76.Value = 0.15F;
            optionalLinearGaugeHand4.TailIndentSize = elementSize76;
            elementSize77.Value = 0.65F;
            optionalLinearGaugeHand4.TipLength = elementSize77;
            elementSize78.Value = 0.2F;
            optionalLinearGaugeHand4.TipWidth = elementSize78;
            elementSize79.Value = 0.03F;
            optionalLinearGaugeHand4.Width = elementSize79;
            this.gaugePortTrim.Hand = optionalLinearGaugeHand4;
            this.gaugePortTrim.InputPin = sinkPin4;
            this.gaugePortTrim.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("gaugePortTrim.InternalData")));
            this.gaugePortTrim.Location = new System.Drawing.Point(238, 47);
            this.gaugePortTrim.Max = 100D;
            this.gaugePortTrim.Min = 0D;
            this.gaugePortTrim.Name = "gaugePortTrim";
            elementSize80.Value = 0.9F;
            linearGaugeRail4.Length = elementSize80;
            elementOffsetSize15.Value = 0.1F;
            elementOffsets8.X = elementOffsetSize15;
            elementOffsetSize16.Value = 0F;
            elementOffsets8.Y = elementOffsetSize16;
            linearGaugeRail4.Position = elementOffsets8;
            elementSize81.Value = 0.08F;
            linearGaugeRail4.Width = elementSize81;
            this.gaugePortTrim.Rail = linearGaugeRail4;
            analogGaugeScaleRanges4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            elementSize82.Value = 0.2F;
            analogGaugeScaleRanges4.Position = elementSize82;
            elementSize83.Value = 0.05F;
            analogGaugeScaleRanges4.Width = elementSize83;
            this.gaugePortTrim.Ranges = analogGaugeScaleRanges4;
            rotation4.Angle = 180F;
            rotation4.Width = 0.7F;
            this.gaugePortTrim.Rotation = rotation4;
            gpBlend27.Blends = gpBlends27;
            gpBlendShape27.Focus = 0.5F;
            gpBlendShape27.Scale = 1F;
            gpBlend27.Shape = gpBlendShape27;
            gpBrush27.Blend = gpBlend27;
            gpBrush27.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor27.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint27.X = 0F;
            gpCenterPoint27.Y = 0F;
            gpCenterColor27.Point = gpCenterPoint27;
            gpGradient27.CenterColor = gpCenterColor27;
            gpGradient27.Colors = gpColors27;
            gpGradient27.Path = gpPoints27;
            gpBrush27.Gradient = gpGradient27;
            gpHatch27.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch27.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush27.Hatch = gpHatch27;
            gpBrush27.InterpolationColors = gpInterpolationColors27;
            instrumentMajorTicks4.Brush = gpBrush27;
            instrumentMajorTicks4.Count = ((uint)(5u));
            instrumentTicksText7.Angle = 0F;
            gpBlend28.Blends = gpBlends28;
            gpBlendShape28.Focus = 0.5F;
            gpBlendShape28.Scale = 1F;
            gpBlend28.Shape = gpBlendShape28;
            gpBrush28.Blend = gpBlend28;
            gpBrush28.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor28.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint28.X = 0F;
            gpCenterPoint28.Y = 0F;
            gpCenterColor28.Point = gpCenterPoint28;
            gpGradient28.CenterColor = gpCenterColor28;
            gpGradient28.Colors = gpColors28;
            gpGradient28.Path = gpPoints28;
            gpBrush28.Gradient = gpGradient28;
            gpHatch28.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch28.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush28.Hatch = gpHatch28;
            gpBrush28.InterpolationColors = gpInterpolationColors28;
            controlFont11.Brush = gpBrush28;
            controlFont11.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont11.InternalData")));
            gpBlend29.Blends = gpBlends29;
            gpBlendShape29.Focus = 0.5F;
            gpBlendShape29.Scale = 1F;
            gpBlend29.Shape = gpBlendShape29;
            gpBrush29.Blend = gpBlend29;
            gpBrush29.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor29.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint29.X = 0F;
            gpCenterPoint29.Y = 0F;
            gpCenterColor29.Point = gpCenterPoint29;
            gpGradient29.CenterColor = gpCenterColor29;
            gpGradient29.Colors = gpColors29;
            gpGradient29.Path = gpPoints29;
            gpBrush29.Gradient = gpGradient29;
            gpHatch29.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch29.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush29.Hatch = gpHatch29;
            gpBrush29.InterpolationColors = gpInterpolationColors29;
            gpOptionalMultiPen11.Brush = gpBrush29;
            gpOptionalMultiPen11.Compound = gpPenCompound11;
            gpDashStyle11.CustomDash = gpCustomDash11;
            gpDashStyle11.Offset = 0F;
            gpOptionalMultiPen11.DashStyle = gpDashStyle11;
            gpOptionalMultiPen11.Enabled = false;
            gpOptionalMultiPen11.MiterLimit = 0F;
            gpOptionalMultiPen11.Width = 1F;
            controlFont11.Pen = gpOptionalMultiPen11;
            elementSize84.Value = 0.09F;
            controlFont11.Size = elementSize84;
            instrumentTicksText7.Font = controlFont11;
            elementSize85.Value = 0.5F;
            instrumentTicksText7.Position = elementSize85;
            instrumentTicksText7.Visible = true;
            instrumentMajorTicks4.Labels = instrumentTicksText7;
            elementSize86.Value = 0.25F;
            instrumentMajorTicks4.Length = elementSize86;
            optionalInstrumentProperty7.Visible = true;
            instrumentEndTick7.TickLabel = optionalInstrumentProperty7;
            instrumentEndTick7.Visible = true;
            instrumentMajorTicks4.MaxTick = instrumentEndTick7;
            optionalInstrumentProperty8.Visible = true;
            instrumentEndTick8.TickLabel = optionalInstrumentProperty8;
            instrumentEndTick8.Visible = true;
            instrumentMajorTicks4.MinTick = instrumentEndTick8;
            elementSize87.Value = 0.01F;
            instrumentMajorTicks4.Thickness = elementSize87;
            instrumentMajorTicks4.Visible = true;
            reversibleGaugeScale4.MajorTicks = instrumentMajorTicks4;
            gpBlend30.Blends = gpBlends30;
            gpBlendShape30.Focus = 0.5F;
            gpBlendShape30.Scale = 1F;
            gpBlend30.Shape = gpBlendShape30;
            gpBrush30.Blend = gpBlend30;
            gpBrush30.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor30.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint30.X = 0F;
            gpCenterPoint30.Y = 0F;
            gpCenterColor30.Point = gpCenterPoint30;
            gpGradient30.CenterColor = gpCenterColor30;
            gpGradient30.Colors = gpColors30;
            gpGradient30.Path = gpPoints30;
            gpBrush30.Gradient = gpGradient30;
            gpHatch30.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch30.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush30.Hatch = gpHatch30;
            gpBrush30.InterpolationColors = gpInterpolationColors30;
            instrumentLabeledTicks4.Brush = gpBrush30;
            instrumentLabeledTicks4.Count = ((uint)(3u));
            instrumentTicksText8.Angle = 0F;
            gpBlend31.Blends = gpBlends31;
            gpBlendShape31.Focus = 0.5F;
            gpBlendShape31.Scale = 1F;
            gpBlend31.Shape = gpBlendShape31;
            gpBrush31.Blend = gpBlend31;
            gpBrush31.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor31.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint31.X = 0F;
            gpCenterPoint31.Y = 0F;
            gpCenterColor31.Point = gpCenterPoint31;
            gpGradient31.CenterColor = gpCenterColor31;
            gpGradient31.Colors = gpColors31;
            gpGradient31.Path = gpPoints31;
            gpBrush31.Gradient = gpGradient31;
            gpHatch31.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch31.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush31.Hatch = gpHatch31;
            gpBrush31.InterpolationColors = gpInterpolationColors31;
            controlFont12.Brush = gpBrush31;
            controlFont12.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont12.InternalData")));
            gpBlend32.Blends = gpBlends32;
            gpBlendShape32.Focus = 0.5F;
            gpBlendShape32.Scale = 1F;
            gpBlend32.Shape = gpBlendShape32;
            gpBrush32.Blend = gpBlend32;
            gpBrush32.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor32.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint32.X = 0F;
            gpCenterPoint32.Y = 0F;
            gpCenterColor32.Point = gpCenterPoint32;
            gpGradient32.CenterColor = gpCenterColor32;
            gpGradient32.Colors = gpColors32;
            gpGradient32.Path = gpPoints32;
            gpBrush32.Gradient = gpGradient32;
            gpHatch32.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch32.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush32.Hatch = gpHatch32;
            gpBrush32.InterpolationColors = gpInterpolationColors32;
            gpOptionalMultiPen12.Brush = gpBrush32;
            gpOptionalMultiPen12.Compound = gpPenCompound12;
            gpDashStyle12.CustomDash = gpCustomDash12;
            gpDashStyle12.Offset = 0F;
            gpOptionalMultiPen12.DashStyle = gpDashStyle12;
            gpOptionalMultiPen12.Enabled = false;
            gpOptionalMultiPen12.MiterLimit = 0F;
            gpOptionalMultiPen12.Width = 1F;
            controlFont12.Pen = gpOptionalMultiPen12;
            elementSize88.Value = 0.065F;
            controlFont12.Size = elementSize88;
            instrumentTicksText8.Font = controlFont12;
            elementSize89.Value = 0.45F;
            instrumentTicksText8.Position = elementSize89;
            instrumentTicksText8.Visible = false;
            instrumentLabeledTicks4.Labels = instrumentTicksText8;
            elementSize90.Value = 0.15F;
            instrumentLabeledTicks4.Length = elementSize90;
            elementSize91.Value = 0.005F;
            instrumentLabeledTicks4.Thickness = elementSize91;
            instrumentLabeledTicks4.Visible = true;
            reversibleGaugeScale4.MinorTicks = instrumentLabeledTicks4;
            elementSize92.Value = 0.25F;
            reversibleGaugeScale4.Position = elementSize92;
            scalePrecision4.FixedPrecision = false;
            scalePrecision4.NumberDigits = ((uint)(2u));
            reversibleGaugeScale4.Precision = scalePrecision4;
            reversibleGaugeScale4.Reversed = true;
            this.gaugePortTrim.Scale = reversibleGaugeScale4;
            this.gaugePortTrim.Size = new System.Drawing.Size(158, 424);
            this.gaugePortTrim.TabIndex = 108;
            this.gaugePortTrim.TabStop = false;
            this.gaugePortTrim.Text = "linearGauge2";
            this.gaugePortTrim.Value = 100D;
            // 
            // label36
            // 
            this.label36.Font = new System.Drawing.Font("Arial", 14F);
            this.label36.ForeColor = System.Drawing.Color.White;
            this.label36.Location = new System.Drawing.Point(167, 4);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(479, 25);
            this.label36.TabIndex = 109;
            this.label36.Text = "TRIM CONTROL";
            this.label36.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Arial", 14F);
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(18, 94);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(199, 25);
            this.label1.TabIndex = 110;
            this.label1.Text = "PORT";
            this.label1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label2
            // 
            this.label2.Font = new System.Drawing.Font("Arial", 14F);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(581, 94);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(199, 25);
            this.label2.TabIndex = 111;
            this.label2.Text = "STBD";
            this.label2.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label5
            // 
            this.label5.Font = new System.Drawing.Font("Arial", 36F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(263, 235);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(102, 46);
            this.label5.TabIndex = 112;
            this.label5.Text = "--";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label3
            // 
            this.label3.Font = new System.Drawing.Font("Arial", 36F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(435, 235);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(102, 46);
            this.label3.TabIndex = 113;
            this.label3.Text = "--";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Black;
            this.panel1.Location = new System.Drawing.Point(261, 78);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(31, 360);
            this.panel1.TabIndex = 114;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.Black;
            this.panel2.Location = new System.Drawing.Point(512, 80);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(33, 360);
            this.panel2.TabIndex = 115;
            // 
            // label4
            // 
            this.label4.BackColor = System.Drawing.Color.Black;
            this.label4.Font = new System.Drawing.Font("Arial", 14F);
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(256, 423);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(70, 25);
            this.label4.TabIndex = 116;
            this.label4.Text = "100%";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label6
            // 
            this.label6.BackColor = System.Drawing.Color.Black;
            this.label6.Font = new System.Drawing.Font("Arial", 14F);
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(272, 246);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(54, 25);
            this.label6.TabIndex = 117;
            this.label6.Text = "50%";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label7
            // 
            this.label7.BackColor = System.Drawing.Color.Black;
            this.label7.Font = new System.Drawing.Font("Arial", 14F);
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(272, 157);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(54, 25);
            this.label7.TabIndex = 118;
            this.label7.Text = "25%";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label8
            // 
            this.label8.BackColor = System.Drawing.Color.Black;
            this.label8.Font = new System.Drawing.Font("Arial", 14F);
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(272, 334);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(54, 25);
            this.label8.TabIndex = 119;
            this.label8.Text = "75%";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label9
            // 
            this.label9.BackColor = System.Drawing.Color.Black;
            this.label9.Font = new System.Drawing.Font("Arial", 14F);
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(272, 69);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(54, 25);
            this.label9.TabIndex = 120;
            this.label9.Text = "0%";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label10
            // 
            this.label10.BackColor = System.Drawing.Color.Black;
            this.label10.Font = new System.Drawing.Font("Arial", 14F);
            this.label10.ForeColor = System.Drawing.Color.White;
            this.label10.Location = new System.Drawing.Point(479, 70);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(54, 25);
            this.label10.TabIndex = 125;
            this.label10.Text = "0%";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label11
            // 
            this.label11.BackColor = System.Drawing.Color.Black;
            this.label11.Font = new System.Drawing.Font("Arial", 14F);
            this.label11.ForeColor = System.Drawing.Color.White;
            this.label11.Location = new System.Drawing.Point(479, 335);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(54, 25);
            this.label11.TabIndex = 124;
            this.label11.Text = "75%";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label12
            // 
            this.label12.BackColor = System.Drawing.Color.Black;
            this.label12.Font = new System.Drawing.Font("Arial", 14F);
            this.label12.ForeColor = System.Drawing.Color.White;
            this.label12.Location = new System.Drawing.Point(479, 158);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(54, 25);
            this.label12.TabIndex = 123;
            this.label12.Text = "25%";
            this.label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label13
            // 
            this.label13.BackColor = System.Drawing.Color.Black;
            this.label13.Font = new System.Drawing.Font("Arial", 14F);
            this.label13.ForeColor = System.Drawing.Color.White;
            this.label13.Location = new System.Drawing.Point(479, 247);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(54, 25);
            this.label13.TabIndex = 122;
            this.label13.Text = "50%";
            this.label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label14
            // 
            this.label14.BackColor = System.Drawing.Color.Black;
            this.label14.Font = new System.Drawing.Font("Arial", 14F);
            this.label14.ForeColor = System.Drawing.Color.White;
            this.label14.Location = new System.Drawing.Point(479, 424);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(70, 25);
            this.label14.TabIndex = 121;
            this.label14.Text = "100%";
            this.label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // btnConfigNmea2000
            // 
            this.btnConfigNmea2000.BackgroundImage = global::WhatTheHelmRuntime.Properties.Resources.BlackButton;
            this.btnConfigNmea2000.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnConfigNmea2000.FlatAppearance.BorderSize = 0;
            this.btnConfigNmea2000.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnConfigNmea2000.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnConfigNmea2000.ForeColor = System.Drawing.Color.White;
            this.btnConfigNmea2000.Location = new System.Drawing.Point(11, 390);
            this.btnConfigNmea2000.Margin = new System.Windows.Forms.Padding(2);
            this.btnConfigNmea2000.Name = "btnConfigNmea2000";
            this.btnConfigNmea2000.Size = new System.Drawing.Size(171, 81);
            this.btnConfigNmea2000.TabIndex = 154;
            this.btnConfigNmea2000.TabStop = false;
            this.btnConfigNmea2000.Text = "NMEA 2000\r\nCONFIGURATION";
            this.btnConfigNmea2000.UseVisualStyleBackColor = true;
            this.btnConfigNmea2000.Click += new System.EventHandler(this.btnConfigNmea2000_Click);
            // 
            // btnPortBowDown
            // 
            this.btnPortBowDown.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPortBowDown.BackgroundImage")));
            this.btnPortBowDown.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPortBowDown.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.btnPortBowDown.FlatAppearance.BorderSize = 0;
            this.btnPortBowDown.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.btnPortBowDown.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.btnPortBowDown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPortBowDown.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPortBowDown.ForeColor = System.Drawing.Color.White;
            this.btnPortBowDown.Function = "PORT TRIM DOWN";
            this.btnPortBowDown.Location = new System.Drawing.Point(18, 251);
            this.btnPortBowDown.MvecAddress = ((byte)(177));
            this.btnPortBowDown.MvecFuseNumber = ((byte)(8));
            this.btnPortBowDown.MvecGrid = ((byte)(0));
            this.btnPortBowDown.MvecRelayNumber = ((byte)(5));
            this.btnPortBowDown.Name = "btnPortBowDown";
            this.btnPortBowDown.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("btnPortBowDown.OffStateBackImage")));
            this.btnPortBowDown.OffStateForeColor = System.Drawing.Color.White;
            this.btnPortBowDown.OffStateText = "BOW\r\nDOWN";
            this.btnPortBowDown.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("btnPortBowDown.OnStateBackImage")));
            this.btnPortBowDown.OnStateForeColor = System.Drawing.Color.White;
            this.btnPortBowDown.OnStateText = "BOW\r\nDOWN";
            this.btnPortBowDown.Size = new System.Drawing.Size(199, 111);
            this.btnPortBowDown.State = false;
            this.btnPortBowDown.TabIndex = 107;
            this.btnPortBowDown.Text = "BOW\r\nDOWN";
            this.btnPortBowDown.UseVisualStyleBackColor = true;
            this.btnPortBowDown.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.btnPortBowDown_NewCommand);
            // 
            // btnPortBowUp
            // 
            this.btnPortBowUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPortBowUp.BackgroundImage")));
            this.btnPortBowUp.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPortBowUp.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.btnPortBowUp.FlatAppearance.BorderSize = 0;
            this.btnPortBowUp.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.btnPortBowUp.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.btnPortBowUp.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPortBowUp.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPortBowUp.ForeColor = System.Drawing.Color.White;
            this.btnPortBowUp.Function = "PORT TRIM UP";
            this.btnPortBowUp.Location = new System.Drawing.Point(18, 134);
            this.btnPortBowUp.MvecAddress = ((byte)(177));
            this.btnPortBowUp.MvecFuseNumber = ((byte)(4));
            this.btnPortBowUp.MvecGrid = ((byte)(0));
            this.btnPortBowUp.MvecRelayNumber = ((byte)(2));
            this.btnPortBowUp.Name = "btnPortBowUp";
            this.btnPortBowUp.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("btnPortBowUp.OffStateBackImage")));
            this.btnPortBowUp.OffStateForeColor = System.Drawing.Color.White;
            this.btnPortBowUp.OffStateText = "BOW\r\nUP";
            this.btnPortBowUp.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("btnPortBowUp.OnStateBackImage")));
            this.btnPortBowUp.OnStateForeColor = System.Drawing.Color.White;
            this.btnPortBowUp.OnStateText = "BOW\r\nUP";
            this.btnPortBowUp.Size = new System.Drawing.Size(199, 111);
            this.btnPortBowUp.State = false;
            this.btnPortBowUp.TabIndex = 106;
            this.btnPortBowUp.Text = "BOW\r\nUP";
            this.btnPortBowUp.UseVisualStyleBackColor = true;
            this.btnPortBowUp.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.btnPortBowUp_NewCommand);
            // 
            // btnStbdBowDown
            // 
            this.btnStbdBowDown.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStbdBowDown.BackgroundImage")));
            this.btnStbdBowDown.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnStbdBowDown.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.btnStbdBowDown.FlatAppearance.BorderSize = 0;
            this.btnStbdBowDown.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.btnStbdBowDown.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.btnStbdBowDown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStbdBowDown.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnStbdBowDown.ForeColor = System.Drawing.Color.White;
            this.btnStbdBowDown.Function = "STBD TRIM DOWN";
            this.btnStbdBowDown.Location = new System.Drawing.Point(581, 251);
            this.btnStbdBowDown.MvecAddress = ((byte)(177));
            this.btnStbdBowDown.MvecFuseNumber = ((byte)(2));
            this.btnStbdBowDown.MvecGrid = ((byte)(0));
            this.btnStbdBowDown.MvecRelayNumber = ((byte)(4));
            this.btnStbdBowDown.Name = "btnStbdBowDown";
            this.btnStbdBowDown.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("btnStbdBowDown.OffStateBackImage")));
            this.btnStbdBowDown.OffStateForeColor = System.Drawing.Color.White;
            this.btnStbdBowDown.OffStateText = "BOW\r\nDOWN";
            this.btnStbdBowDown.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("btnStbdBowDown.OnStateBackImage")));
            this.btnStbdBowDown.OnStateForeColor = System.Drawing.Color.White;
            this.btnStbdBowDown.OnStateText = "BOW\r\nDOWN";
            this.btnStbdBowDown.Size = new System.Drawing.Size(199, 111);
            this.btnStbdBowDown.State = false;
            this.btnStbdBowDown.TabIndex = 105;
            this.btnStbdBowDown.Text = "BOW\r\nDOWN";
            this.btnStbdBowDown.UseVisualStyleBackColor = true;
            this.btnStbdBowDown.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.btnStbBowDown_NewCommand);
            // 
            // btnStbdBowUp
            // 
            this.btnStbdBowUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStbdBowUp.BackgroundImage")));
            this.btnStbdBowUp.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnStbdBowUp.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.btnStbdBowUp.FlatAppearance.BorderSize = 0;
            this.btnStbdBowUp.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.btnStbdBowUp.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.btnStbdBowUp.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStbdBowUp.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnStbdBowUp.ForeColor = System.Drawing.Color.White;
            this.btnStbdBowUp.Function = "STBD TRIM UP";
            this.btnStbdBowUp.Location = new System.Drawing.Point(581, 134);
            this.btnStbdBowUp.MvecAddress = ((byte)(177));
            this.btnStbdBowUp.MvecFuseNumber = ((byte)(1));
            this.btnStbdBowUp.MvecGrid = ((byte)(0));
            this.btnStbdBowUp.MvecRelayNumber = ((byte)(1));
            this.btnStbdBowUp.Name = "btnStbdBowUp";
            this.btnStbdBowUp.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("btnStbdBowUp.OffStateBackImage")));
            this.btnStbdBowUp.OffStateForeColor = System.Drawing.Color.White;
            this.btnStbdBowUp.OffStateText = "BOW\r\nUP";
            this.btnStbdBowUp.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("btnStbdBowUp.OnStateBackImage")));
            this.btnStbdBowUp.OnStateForeColor = System.Drawing.Color.White;
            this.btnStbdBowUp.OnStateText = "BOW\r\nUP";
            this.btnStbdBowUp.Size = new System.Drawing.Size(199, 111);
            this.btnStbdBowUp.State = false;
            this.btnStbdBowUp.TabIndex = 104;
            this.btnStbdBowUp.Text = "BOW\r\nUP";
            this.btnStbdBowUp.UseVisualStyleBackColor = true;
            this.btnStbdBowUp.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.btnStbBowUp_NewCommand);
            // 
            // btnSync
            // 
            this.btnSync.BackgroundImage = global::WhatTheHelmRuntime.Properties.Resources.BlackButton;
            this.btnSync.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnSync.FlatAppearance.BorderSize = 0;
            this.btnSync.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSync.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSync.ForeColor = System.Drawing.Color.White;
            this.btnSync.Location = new System.Drawing.Point(588, 396);
            this.btnSync.Name = "btnSync";
            this.btnSync.Size = new System.Drawing.Size(199, 72);
            this.btnSync.TabIndex = 155;
            this.btnSync.Text = "SYNC";
            this.btnSync.UseVisualStyleBackColor = true;
            this.btnSync.MouseUp += new System.Windows.Forms.MouseEventHandler(this.btnSync_MouseUp);
            // 
            // TrimControl
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.Controls.Add(this.btnSync);
            this.Controls.Add(this.btnConfigNmea2000);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.gaugePortTrim);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label36);
            this.Controls.Add(this.btnPortBowDown);
            this.Controls.Add(this.btnPortBowUp);
            this.Controls.Add(this.btnStbdBowDown);
            this.Controls.Add(this.btnStbdBowUp);
            this.Controls.Add(this.gaugeStbdTrim);
            this.Controls.Add(this.label3);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "TrimControl";
            this.Text = "TrimControl";
            ((System.ComponentModel.ISupportInitialize)(this.gaugeStbdTrim)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gaugePortTrim)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Mitov.InstrumentLab.LinearGauge gaugeStbdTrim;
        private BoatFormsLib.CustomUserControls.DashboardButton btnStbdBowUp;
        private BoatFormsLib.CustomUserControls.DashboardButton btnStbdBowDown;
        private BoatFormsLib.CustomUserControls.DashboardButton btnPortBowDown;
        private BoatFormsLib.CustomUserControls.DashboardButton btnPortBowUp;
        private Mitov.InstrumentLab.LinearGauge gaugePortTrim;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Button btnConfigNmea2000;
        private System.Windows.Forms.Button btnSync;
    }
}