namespace WhatTheHelmRuntime
{
    partial class TrimControl
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Mitov.BasicLab.ControlBackground controlBackground7 = new Mitov.BasicLab.ControlBackground();
            Mitov.BasicLab.RectControlBorder rectControlBorder7 = new Mitov.BasicLab.RectControlBorder();
            Mitov.BasicLab.ControlInnerBevel controlInnerBevel7 = new Mitov.BasicLab.ControlInnerBevel();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TrimControl));
            Mitov.BasicLab.ElementSize elementSize139 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ControlBevel controlBevel7 = new Mitov.BasicLab.ControlBevel();
            Mitov.BasicLab.ElementSize elementSize140 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize141 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize142 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.VerticalCaption verticalCaption7 = new Mitov.BasicLab.VerticalCaption();
            Mitov.BasicLab.ControlFont controlFont19 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush49 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend49 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends49 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape49 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient49 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor49 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint49 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors49 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints49 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch49 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors49 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen19 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush50 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend50 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends50 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape50 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient50 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor50 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint50 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors50 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints50 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch50 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors50 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound19 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle19 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash19 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize143 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets13 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize25 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize26 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.InstrumentLab.Glass glass7 = new Mitov.InstrumentLab.Glass();
            Mitov.InstrumentLab.OptionalLinearGaugeHand optionalLinearGaugeHand7 = new Mitov.InstrumentLab.OptionalLinearGaugeHand();
            Mitov.InstrumentLab.HandAnimation handAnimation7 = new Mitov.InstrumentLab.HandAnimation();
            Mitov.BasicLab.ElementSize elementSize144 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ElementShadow elementShadow7 = new Mitov.InstrumentLab.ElementShadow();
            Mitov.BasicLab.ElementSize elementSize145 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize146 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize147 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize148 = new Mitov.BasicLab.ElementSize();
            OpenWire.Proxy.SinkPin sinkPin7 = new OpenWire.Proxy.SinkPin();
            Mitov.InstrumentLab.LinearGaugeRail linearGaugeRail7 = new Mitov.InstrumentLab.LinearGaugeRail();
            Mitov.BasicLab.ElementSize elementSize149 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets14 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize27 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize28 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementSize elementSize150 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.AnalogGaugeScaleRanges analogGaugeScaleRanges7 = new Mitov.InstrumentLab.AnalogGaugeScaleRanges();
            Mitov.BasicLab.ElementSize elementSize151 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize152 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.Rotation rotation7 = new Mitov.InstrumentLab.Rotation();
            Mitov.InstrumentLab.ReversibleGaugeScale reversibleGaugeScale7 = new Mitov.InstrumentLab.ReversibleGaugeScale();
            Mitov.InstrumentLab.InstrumentMajorTicks instrumentMajorTicks7 = new Mitov.InstrumentLab.InstrumentMajorTicks();
            Mitov.BasicLab.GPBrush gpBrush51 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend51 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends51 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape51 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient51 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor51 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint51 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors51 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints51 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch51 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors51 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText13 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont20 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush52 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend52 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends52 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape52 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient52 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor52 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint52 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors52 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints52 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch52 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors52 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen20 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush53 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend53 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends53 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape53 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient53 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor53 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint53 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors53 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints53 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch53 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors53 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound20 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle20 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash20 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize153 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize154 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize155 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick13 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty13 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick14 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty14 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.BasicLab.ElementSize elementSize156 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentLabeledTicks instrumentLabeledTicks7 = new Mitov.InstrumentLab.InstrumentLabeledTicks();
            Mitov.BasicLab.GPBrush gpBrush54 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend54 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends54 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape54 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient54 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor54 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint54 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors54 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints54 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch54 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors54 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText14 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont21 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush55 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend55 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends55 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape55 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient55 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor55 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint55 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors55 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints55 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch55 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors55 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen21 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush56 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend56 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends56 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape56 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient56 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor56 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint56 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors56 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints56 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch56 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors56 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound21 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle21 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash21 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize157 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize158 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize159 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize160 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize161 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ScalePrecision scalePrecision7 = new Mitov.InstrumentLab.ScalePrecision();
            Mitov.BasicLab.ControlBackground controlBackground8 = new Mitov.BasicLab.ControlBackground();
            Mitov.BasicLab.RectControlBorder rectControlBorder8 = new Mitov.BasicLab.RectControlBorder();
            Mitov.BasicLab.ControlInnerBevel controlInnerBevel8 = new Mitov.BasicLab.ControlInnerBevel();
            Mitov.BasicLab.ElementSize elementSize162 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ControlBevel controlBevel8 = new Mitov.BasicLab.ControlBevel();
            Mitov.BasicLab.ElementSize elementSize163 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize164 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize165 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.VerticalCaption verticalCaption8 = new Mitov.BasicLab.VerticalCaption();
            Mitov.BasicLab.ControlFont controlFont22 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush57 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend57 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends57 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape57 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient57 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor57 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint57 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors57 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints57 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch57 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors57 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen22 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush58 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend58 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends58 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape58 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient58 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor58 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint58 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors58 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints58 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch58 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors58 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound22 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle22 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash22 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize166 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets15 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize29 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize30 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.InstrumentLab.Glass glass8 = new Mitov.InstrumentLab.Glass();
            Mitov.InstrumentLab.OptionalLinearGaugeHand optionalLinearGaugeHand8 = new Mitov.InstrumentLab.OptionalLinearGaugeHand();
            Mitov.InstrumentLab.HandAnimation handAnimation8 = new Mitov.InstrumentLab.HandAnimation();
            Mitov.BasicLab.ElementSize elementSize167 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ElementShadow elementShadow8 = new Mitov.InstrumentLab.ElementShadow();
            Mitov.BasicLab.ElementSize elementSize168 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize169 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize170 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize171 = new Mitov.BasicLab.ElementSize();
            OpenWire.Proxy.SinkPin sinkPin8 = new OpenWire.Proxy.SinkPin();
            Mitov.InstrumentLab.LinearGaugeRail linearGaugeRail8 = new Mitov.InstrumentLab.LinearGaugeRail();
            Mitov.BasicLab.ElementSize elementSize172 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets16 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize31 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize32 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementSize elementSize173 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.AnalogGaugeScaleRanges analogGaugeScaleRanges8 = new Mitov.InstrumentLab.AnalogGaugeScaleRanges();
            Mitov.BasicLab.ElementSize elementSize174 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize175 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.Rotation rotation8 = new Mitov.InstrumentLab.Rotation();
            Mitov.InstrumentLab.ReversibleGaugeScale reversibleGaugeScale8 = new Mitov.InstrumentLab.ReversibleGaugeScale();
            Mitov.InstrumentLab.InstrumentMajorTicks instrumentMajorTicks8 = new Mitov.InstrumentLab.InstrumentMajorTicks();
            Mitov.BasicLab.GPBrush gpBrush59 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend59 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends59 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape59 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient59 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor59 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint59 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors59 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints59 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch59 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors59 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText15 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont23 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush60 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend60 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends60 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape60 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient60 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor60 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint60 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors60 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints60 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch60 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors60 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen23 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush61 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend61 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends61 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape61 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient61 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor61 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint61 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors61 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints61 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch61 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors61 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound23 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle23 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash23 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize176 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize177 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize178 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick15 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty15 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick16 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty16 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.BasicLab.ElementSize elementSize179 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentLabeledTicks instrumentLabeledTicks8 = new Mitov.InstrumentLab.InstrumentLabeledTicks();
            Mitov.BasicLab.GPBrush gpBrush62 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend62 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends62 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape62 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient62 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor62 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint62 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors62 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints62 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch62 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors62 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText16 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont24 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush63 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend63 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends63 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape63 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient63 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor63 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint63 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors63 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints63 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch63 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors63 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen24 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush64 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend64 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends64 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape64 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient64 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor64 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint64 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors64 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints64 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch64 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors64 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound24 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle24 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash24 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize180 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize181 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize182 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize183 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize184 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ScalePrecision scalePrecision8 = new Mitov.InstrumentLab.ScalePrecision();
            this.gaugeStbdTrim = new Mitov.InstrumentLab.LinearGauge(this.components);
            this.gaugePortTrim = new Mitov.InstrumentLab.LinearGauge(this.components);
            this.label36 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.label4 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.dashboardButton2 = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.dashboardButton3 = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.dashboardButton1 = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.dashboardButton7 = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.btnConfigNmea2000 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.gaugeStbdTrim)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gaugePortTrim)).BeginInit();
            this.SuspendLayout();
            // 
            // gaugeStbdTrim
            // 
            controlBackground7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.gaugeStbdTrim.Background = controlBackground7;
            controlInnerBevel7.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlInnerBevel7.InternalData")));
            elementSize139.Value = 0.05F;
            controlInnerBevel7.Width = elementSize139;
            rectControlBorder7.BevelInner = controlInnerBevel7;
            elementSize140.Value = 0.05F;
            controlBevel7.Width = elementSize140;
            rectControlBorder7.BevelOuter = controlBevel7;
            rectControlBorder7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            elementSize141.Value = 0.2F;
            rectControlBorder7.CornerRadius = elementSize141;
            rectControlBorder7.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("rectControlBorder7.InternalData")));
            elementSize142.Value = 0F;
            rectControlBorder7.Width = elementSize142;
            this.gaugeStbdTrim.Border = rectControlBorder7;
            verticalCaption7.Angle = 0F;
            gpBlend49.Blends = gpBlends49;
            gpBlendShape49.Focus = 0.5F;
            gpBlendShape49.Scale = 1F;
            gpBlend49.Shape = gpBlendShape49;
            gpBrush49.Blend = gpBlend49;
            gpBrush49.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor49.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint49.X = 0F;
            gpCenterPoint49.Y = 0F;
            gpCenterColor49.Point = gpCenterPoint49;
            gpGradient49.CenterColor = gpCenterColor49;
            gpGradient49.Colors = gpColors49;
            gpGradient49.Path = gpPoints49;
            gpBrush49.Gradient = gpGradient49;
            gpHatch49.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch49.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush49.Hatch = gpHatch49;
            gpBrush49.InterpolationColors = gpInterpolationColors49;
            controlFont19.Brush = gpBrush49;
            controlFont19.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont19.InternalData")));
            gpBlend50.Blends = gpBlends50;
            gpBlendShape50.Focus = 0.5F;
            gpBlendShape50.Scale = 1F;
            gpBlend50.Shape = gpBlendShape50;
            gpBrush50.Blend = gpBlend50;
            gpBrush50.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor50.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint50.X = 0F;
            gpCenterPoint50.Y = 0F;
            gpCenterColor50.Point = gpCenterPoint50;
            gpGradient50.CenterColor = gpCenterColor50;
            gpGradient50.Colors = gpColors50;
            gpGradient50.Path = gpPoints50;
            gpBrush50.Gradient = gpGradient50;
            gpHatch50.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch50.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush50.Hatch = gpHatch50;
            gpBrush50.InterpolationColors = gpInterpolationColors50;
            gpOptionalMultiPen19.Brush = gpBrush50;
            gpOptionalMultiPen19.Compound = gpPenCompound19;
            gpDashStyle19.CustomDash = gpCustomDash19;
            gpDashStyle19.Offset = 0F;
            gpOptionalMultiPen19.DashStyle = gpDashStyle19;
            gpOptionalMultiPen19.Enabled = false;
            gpOptionalMultiPen19.MiterLimit = 0F;
            gpOptionalMultiPen19.Width = 1F;
            controlFont19.Pen = gpOptionalMultiPen19;
            elementSize143.Value = 0.25F;
            controlFont19.Size = elementSize143;
            verticalCaption7.Font = controlFont19;
            elementOffsetSize25.Value = 0.8F;
            elementOffsets13.X = elementOffsetSize25;
            elementOffsetSize26.Value = 0F;
            elementOffsets13.Y = elementOffsetSize26;
            verticalCaption7.Position = elementOffsets13;
            this.gaugeStbdTrim.Caption = verticalCaption7;
            this.gaugeStbdTrim.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.gaugeStbdTrim.Curved = false;
            glass7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            glass7.Visible = false;
            this.gaugeStbdTrim.Glass = glass7;
            handAnimation7.Acceleration = 0.015F;
            handAnimation7.Resistance = 0.16F;
            optionalLinearGaugeHand7.Animation = handAnimation7;
            optionalLinearGaugeHand7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            elementSize144.Value = 0.33F;
            optionalLinearGaugeHand7.Length = elementSize144;
            optionalLinearGaugeHand7.Shadow = elementShadow7;
            elementSize145.Value = 0.15F;
            optionalLinearGaugeHand7.TailIndentSize = elementSize145;
            elementSize146.Value = 0.65F;
            optionalLinearGaugeHand7.TipLength = elementSize146;
            elementSize147.Value = 0.2F;
            optionalLinearGaugeHand7.TipWidth = elementSize147;
            elementSize148.Value = 0.03F;
            optionalLinearGaugeHand7.Width = elementSize148;
            this.gaugeStbdTrim.Hand = optionalLinearGaugeHand7;
            this.gaugeStbdTrim.InputPin = sinkPin7;
            this.gaugeStbdTrim.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("gaugeStbdTrim.InternalData")));
            this.gaugeStbdTrim.Location = new System.Drawing.Point(409, 44);
            this.gaugeStbdTrim.Max = 0D;
            this.gaugeStbdTrim.Min = 100D;
            this.gaugeStbdTrim.Name = "gaugeStbdTrim";
            elementSize149.Value = 0.9F;
            linearGaugeRail7.Length = elementSize149;
            elementOffsetSize27.Value = 0.1F;
            elementOffsets14.X = elementOffsetSize27;
            elementOffsetSize28.Value = 0F;
            elementOffsets14.Y = elementOffsetSize28;
            linearGaugeRail7.Position = elementOffsets14;
            elementSize150.Value = 0.08F;
            linearGaugeRail7.Width = elementSize150;
            this.gaugeStbdTrim.Rail = linearGaugeRail7;
            analogGaugeScaleRanges7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            elementSize151.Value = 0.2F;
            analogGaugeScaleRanges7.Position = elementSize151;
            elementSize152.Value = 0.05F;
            analogGaugeScaleRanges7.Width = elementSize152;
            this.gaugeStbdTrim.Ranges = analogGaugeScaleRanges7;
            rotation7.Angle = 0F;
            rotation7.Width = 0.7F;
            this.gaugeStbdTrim.Rotation = rotation7;
            gpBlend51.Blends = gpBlends51;
            gpBlendShape51.Focus = 0.5F;
            gpBlendShape51.Scale = 1F;
            gpBlend51.Shape = gpBlendShape51;
            gpBrush51.Blend = gpBlend51;
            gpBrush51.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor51.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint51.X = 0F;
            gpCenterPoint51.Y = 0F;
            gpCenterColor51.Point = gpCenterPoint51;
            gpGradient51.CenterColor = gpCenterColor51;
            gpGradient51.Colors = gpColors51;
            gpGradient51.Path = gpPoints51;
            gpBrush51.Gradient = gpGradient51;
            gpHatch51.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch51.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush51.Hatch = gpHatch51;
            gpBrush51.InterpolationColors = gpInterpolationColors51;
            instrumentMajorTicks7.Brush = gpBrush51;
            instrumentMajorTicks7.Count = ((uint)(5u));
            instrumentTicksText13.Angle = 0F;
            gpBlend52.Blends = gpBlends52;
            gpBlendShape52.Focus = 0.5F;
            gpBlendShape52.Scale = 1F;
            gpBlend52.Shape = gpBlendShape52;
            gpBrush52.Blend = gpBlend52;
            gpBrush52.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor52.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint52.X = 0F;
            gpCenterPoint52.Y = 0F;
            gpCenterColor52.Point = gpCenterPoint52;
            gpGradient52.CenterColor = gpCenterColor52;
            gpGradient52.Colors = gpColors52;
            gpGradient52.Path = gpPoints52;
            gpBrush52.Gradient = gpGradient52;
            gpHatch52.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch52.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush52.Hatch = gpHatch52;
            gpBrush52.InterpolationColors = gpInterpolationColors52;
            controlFont20.Brush = gpBrush52;
            controlFont20.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont20.InternalData")));
            gpBlend53.Blends = gpBlends53;
            gpBlendShape53.Focus = 0.5F;
            gpBlendShape53.Scale = 1F;
            gpBlend53.Shape = gpBlendShape53;
            gpBrush53.Blend = gpBlend53;
            gpBrush53.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor53.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint53.X = 0F;
            gpCenterPoint53.Y = 0F;
            gpCenterColor53.Point = gpCenterPoint53;
            gpGradient53.CenterColor = gpCenterColor53;
            gpGradient53.Colors = gpColors53;
            gpGradient53.Path = gpPoints53;
            gpBrush53.Gradient = gpGradient53;
            gpHatch53.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch53.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush53.Hatch = gpHatch53;
            gpBrush53.InterpolationColors = gpInterpolationColors53;
            gpOptionalMultiPen20.Brush = gpBrush53;
            gpOptionalMultiPen20.Compound = gpPenCompound20;
            gpDashStyle20.CustomDash = gpCustomDash20;
            gpDashStyle20.Offset = 0F;
            gpOptionalMultiPen20.DashStyle = gpDashStyle20;
            gpOptionalMultiPen20.Enabled = false;
            gpOptionalMultiPen20.MiterLimit = 0F;
            gpOptionalMultiPen20.Width = 1F;
            controlFont20.Pen = gpOptionalMultiPen20;
            elementSize153.Value = 0.09F;
            controlFont20.Size = elementSize153;
            instrumentTicksText13.Font = controlFont20;
            elementSize154.Value = 0.5F;
            instrumentTicksText13.Position = elementSize154;
            instrumentTicksText13.Visible = true;
            instrumentMajorTicks7.Labels = instrumentTicksText13;
            elementSize155.Value = 0.25F;
            instrumentMajorTicks7.Length = elementSize155;
            optionalInstrumentProperty13.Visible = true;
            instrumentEndTick13.TickLabel = optionalInstrumentProperty13;
            instrumentEndTick13.Visible = true;
            instrumentMajorTicks7.MaxTick = instrumentEndTick13;
            optionalInstrumentProperty14.Visible = true;
            instrumentEndTick14.TickLabel = optionalInstrumentProperty14;
            instrumentEndTick14.Visible = true;
            instrumentMajorTicks7.MinTick = instrumentEndTick14;
            elementSize156.Value = 0.01F;
            instrumentMajorTicks7.Thickness = elementSize156;
            instrumentMajorTicks7.Visible = true;
            reversibleGaugeScale7.MajorTicks = instrumentMajorTicks7;
            gpBlend54.Blends = gpBlends54;
            gpBlendShape54.Focus = 0.5F;
            gpBlendShape54.Scale = 1F;
            gpBlend54.Shape = gpBlendShape54;
            gpBrush54.Blend = gpBlend54;
            gpBrush54.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor54.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint54.X = 0F;
            gpCenterPoint54.Y = 0F;
            gpCenterColor54.Point = gpCenterPoint54;
            gpGradient54.CenterColor = gpCenterColor54;
            gpGradient54.Colors = gpColors54;
            gpGradient54.Path = gpPoints54;
            gpBrush54.Gradient = gpGradient54;
            gpHatch54.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch54.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush54.Hatch = gpHatch54;
            gpBrush54.InterpolationColors = gpInterpolationColors54;
            instrumentLabeledTicks7.Brush = gpBrush54;
            instrumentLabeledTicks7.Count = ((uint)(3u));
            instrumentTicksText14.Angle = 0F;
            gpBlend55.Blends = gpBlends55;
            gpBlendShape55.Focus = 0.5F;
            gpBlendShape55.Scale = 1F;
            gpBlend55.Shape = gpBlendShape55;
            gpBrush55.Blend = gpBlend55;
            gpBrush55.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor55.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint55.X = 0F;
            gpCenterPoint55.Y = 0F;
            gpCenterColor55.Point = gpCenterPoint55;
            gpGradient55.CenterColor = gpCenterColor55;
            gpGradient55.Colors = gpColors55;
            gpGradient55.Path = gpPoints55;
            gpBrush55.Gradient = gpGradient55;
            gpHatch55.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch55.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush55.Hatch = gpHatch55;
            gpBrush55.InterpolationColors = gpInterpolationColors55;
            controlFont21.Brush = gpBrush55;
            controlFont21.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont21.InternalData")));
            gpBlend56.Blends = gpBlends56;
            gpBlendShape56.Focus = 0.5F;
            gpBlendShape56.Scale = 1F;
            gpBlend56.Shape = gpBlendShape56;
            gpBrush56.Blend = gpBlend56;
            gpBrush56.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor56.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint56.X = 0F;
            gpCenterPoint56.Y = 0F;
            gpCenterColor56.Point = gpCenterPoint56;
            gpGradient56.CenterColor = gpCenterColor56;
            gpGradient56.Colors = gpColors56;
            gpGradient56.Path = gpPoints56;
            gpBrush56.Gradient = gpGradient56;
            gpHatch56.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch56.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush56.Hatch = gpHatch56;
            gpBrush56.InterpolationColors = gpInterpolationColors56;
            gpOptionalMultiPen21.Brush = gpBrush56;
            gpOptionalMultiPen21.Compound = gpPenCompound21;
            gpDashStyle21.CustomDash = gpCustomDash21;
            gpDashStyle21.Offset = 0F;
            gpOptionalMultiPen21.DashStyle = gpDashStyle21;
            gpOptionalMultiPen21.Enabled = false;
            gpOptionalMultiPen21.MiterLimit = 0F;
            gpOptionalMultiPen21.Width = 1F;
            controlFont21.Pen = gpOptionalMultiPen21;
            elementSize157.Value = 0.065F;
            controlFont21.Size = elementSize157;
            instrumentTicksText14.Font = controlFont21;
            elementSize158.Value = 0.45F;
            instrumentTicksText14.Position = elementSize158;
            instrumentTicksText14.Visible = false;
            instrumentLabeledTicks7.Labels = instrumentTicksText14;
            elementSize159.Value = 0.15F;
            instrumentLabeledTicks7.Length = elementSize159;
            elementSize160.Value = 0.005F;
            instrumentLabeledTicks7.Thickness = elementSize160;
            instrumentLabeledTicks7.Visible = true;
            reversibleGaugeScale7.MinorTicks = instrumentLabeledTicks7;
            elementSize161.Value = 0.25F;
            reversibleGaugeScale7.Position = elementSize161;
            scalePrecision7.FixedPrecision = false;
            scalePrecision7.NumberDigits = ((uint)(2u));
            reversibleGaugeScale7.Precision = scalePrecision7;
            this.gaugeStbdTrim.Scale = reversibleGaugeScale7;
            this.gaugeStbdTrim.Size = new System.Drawing.Size(158, 424);
            this.gaugeStbdTrim.TabIndex = 0;
            this.gaugeStbdTrim.TabStop = false;
            this.gaugeStbdTrim.Text = "linearGauge1";
            this.gaugeStbdTrim.Value = 0D;
            // 
            // gaugePortTrim
            // 
            controlBackground8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.gaugePortTrim.Background = controlBackground8;
            controlInnerBevel8.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlInnerBevel8.InternalData")));
            elementSize162.Value = 0.05F;
            controlInnerBevel8.Width = elementSize162;
            rectControlBorder8.BevelInner = controlInnerBevel8;
            elementSize163.Value = 0.05F;
            controlBevel8.Width = elementSize163;
            rectControlBorder8.BevelOuter = controlBevel8;
            rectControlBorder8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            elementSize164.Value = 0.2F;
            rectControlBorder8.CornerRadius = elementSize164;
            rectControlBorder8.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("rectControlBorder8.InternalData")));
            elementSize165.Value = 0F;
            rectControlBorder8.Width = elementSize165;
            this.gaugePortTrim.Border = rectControlBorder8;
            verticalCaption8.Angle = 0F;
            gpBlend57.Blends = gpBlends57;
            gpBlendShape57.Focus = 0.5F;
            gpBlendShape57.Scale = 1F;
            gpBlend57.Shape = gpBlendShape57;
            gpBrush57.Blend = gpBlend57;
            gpBrush57.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor57.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint57.X = 0F;
            gpCenterPoint57.Y = 0F;
            gpCenterColor57.Point = gpCenterPoint57;
            gpGradient57.CenterColor = gpCenterColor57;
            gpGradient57.Colors = gpColors57;
            gpGradient57.Path = gpPoints57;
            gpBrush57.Gradient = gpGradient57;
            gpHatch57.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch57.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush57.Hatch = gpHatch57;
            gpBrush57.InterpolationColors = gpInterpolationColors57;
            controlFont22.Brush = gpBrush57;
            controlFont22.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont22.InternalData")));
            gpBlend58.Blends = gpBlends58;
            gpBlendShape58.Focus = 0.5F;
            gpBlendShape58.Scale = 1F;
            gpBlend58.Shape = gpBlendShape58;
            gpBrush58.Blend = gpBlend58;
            gpBrush58.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor58.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint58.X = 0F;
            gpCenterPoint58.Y = 0F;
            gpCenterColor58.Point = gpCenterPoint58;
            gpGradient58.CenterColor = gpCenterColor58;
            gpGradient58.Colors = gpColors58;
            gpGradient58.Path = gpPoints58;
            gpBrush58.Gradient = gpGradient58;
            gpHatch58.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch58.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush58.Hatch = gpHatch58;
            gpBrush58.InterpolationColors = gpInterpolationColors58;
            gpOptionalMultiPen22.Brush = gpBrush58;
            gpOptionalMultiPen22.Compound = gpPenCompound22;
            gpDashStyle22.CustomDash = gpCustomDash22;
            gpDashStyle22.Offset = 0F;
            gpOptionalMultiPen22.DashStyle = gpDashStyle22;
            gpOptionalMultiPen22.Enabled = false;
            gpOptionalMultiPen22.MiterLimit = 0F;
            gpOptionalMultiPen22.Width = 1F;
            controlFont22.Pen = gpOptionalMultiPen22;
            elementSize166.Value = 0.25F;
            controlFont22.Size = elementSize166;
            verticalCaption8.Font = controlFont22;
            elementOffsetSize29.Value = 0.8F;
            elementOffsets15.X = elementOffsetSize29;
            elementOffsetSize30.Value = 0F;
            elementOffsets15.Y = elementOffsetSize30;
            verticalCaption8.Position = elementOffsets15;
            this.gaugePortTrim.Caption = verticalCaption8;
            this.gaugePortTrim.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.gaugePortTrim.Curved = false;
            glass8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            glass8.Visible = false;
            this.gaugePortTrim.Glass = glass8;
            handAnimation8.Acceleration = 0.015F;
            handAnimation8.Resistance = 0.16F;
            optionalLinearGaugeHand8.Animation = handAnimation8;
            optionalLinearGaugeHand8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            elementSize167.Value = 0.33F;
            optionalLinearGaugeHand8.Length = elementSize167;
            optionalLinearGaugeHand8.Shadow = elementShadow8;
            elementSize168.Value = 0.15F;
            optionalLinearGaugeHand8.TailIndentSize = elementSize168;
            elementSize169.Value = 0.65F;
            optionalLinearGaugeHand8.TipLength = elementSize169;
            elementSize170.Value = 0.2F;
            optionalLinearGaugeHand8.TipWidth = elementSize170;
            elementSize171.Value = 0.03F;
            optionalLinearGaugeHand8.Width = elementSize171;
            this.gaugePortTrim.Hand = optionalLinearGaugeHand8;
            this.gaugePortTrim.InputPin = sinkPin8;
            this.gaugePortTrim.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("gaugePortTrim.InternalData")));
            this.gaugePortTrim.Location = new System.Drawing.Point(239, 44);
            this.gaugePortTrim.Max = 100D;
            this.gaugePortTrim.Min = 0D;
            this.gaugePortTrim.Name = "gaugePortTrim";
            elementSize172.Value = 0.9F;
            linearGaugeRail8.Length = elementSize172;
            elementOffsetSize31.Value = 0.1F;
            elementOffsets16.X = elementOffsetSize31;
            elementOffsetSize32.Value = 0F;
            elementOffsets16.Y = elementOffsetSize32;
            linearGaugeRail8.Position = elementOffsets16;
            elementSize173.Value = 0.08F;
            linearGaugeRail8.Width = elementSize173;
            this.gaugePortTrim.Rail = linearGaugeRail8;
            analogGaugeScaleRanges8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            elementSize174.Value = 0.2F;
            analogGaugeScaleRanges8.Position = elementSize174;
            elementSize175.Value = 0.05F;
            analogGaugeScaleRanges8.Width = elementSize175;
            this.gaugePortTrim.Ranges = analogGaugeScaleRanges8;
            rotation8.Angle = 180F;
            rotation8.Width = 0.7F;
            this.gaugePortTrim.Rotation = rotation8;
            gpBlend59.Blends = gpBlends59;
            gpBlendShape59.Focus = 0.5F;
            gpBlendShape59.Scale = 1F;
            gpBlend59.Shape = gpBlendShape59;
            gpBrush59.Blend = gpBlend59;
            gpBrush59.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor59.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint59.X = 0F;
            gpCenterPoint59.Y = 0F;
            gpCenterColor59.Point = gpCenterPoint59;
            gpGradient59.CenterColor = gpCenterColor59;
            gpGradient59.Colors = gpColors59;
            gpGradient59.Path = gpPoints59;
            gpBrush59.Gradient = gpGradient59;
            gpHatch59.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch59.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush59.Hatch = gpHatch59;
            gpBrush59.InterpolationColors = gpInterpolationColors59;
            instrumentMajorTicks8.Brush = gpBrush59;
            instrumentMajorTicks8.Count = ((uint)(5u));
            instrumentTicksText15.Angle = 0F;
            gpBlend60.Blends = gpBlends60;
            gpBlendShape60.Focus = 0.5F;
            gpBlendShape60.Scale = 1F;
            gpBlend60.Shape = gpBlendShape60;
            gpBrush60.Blend = gpBlend60;
            gpBrush60.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor60.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint60.X = 0F;
            gpCenterPoint60.Y = 0F;
            gpCenterColor60.Point = gpCenterPoint60;
            gpGradient60.CenterColor = gpCenterColor60;
            gpGradient60.Colors = gpColors60;
            gpGradient60.Path = gpPoints60;
            gpBrush60.Gradient = gpGradient60;
            gpHatch60.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch60.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush60.Hatch = gpHatch60;
            gpBrush60.InterpolationColors = gpInterpolationColors60;
            controlFont23.Brush = gpBrush60;
            controlFont23.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont23.InternalData")));
            gpBlend61.Blends = gpBlends61;
            gpBlendShape61.Focus = 0.5F;
            gpBlendShape61.Scale = 1F;
            gpBlend61.Shape = gpBlendShape61;
            gpBrush61.Blend = gpBlend61;
            gpBrush61.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor61.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint61.X = 0F;
            gpCenterPoint61.Y = 0F;
            gpCenterColor61.Point = gpCenterPoint61;
            gpGradient61.CenterColor = gpCenterColor61;
            gpGradient61.Colors = gpColors61;
            gpGradient61.Path = gpPoints61;
            gpBrush61.Gradient = gpGradient61;
            gpHatch61.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch61.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush61.Hatch = gpHatch61;
            gpBrush61.InterpolationColors = gpInterpolationColors61;
            gpOptionalMultiPen23.Brush = gpBrush61;
            gpOptionalMultiPen23.Compound = gpPenCompound23;
            gpDashStyle23.CustomDash = gpCustomDash23;
            gpDashStyle23.Offset = 0F;
            gpOptionalMultiPen23.DashStyle = gpDashStyle23;
            gpOptionalMultiPen23.Enabled = false;
            gpOptionalMultiPen23.MiterLimit = 0F;
            gpOptionalMultiPen23.Width = 1F;
            controlFont23.Pen = gpOptionalMultiPen23;
            elementSize176.Value = 0.09F;
            controlFont23.Size = elementSize176;
            instrumentTicksText15.Font = controlFont23;
            elementSize177.Value = 0.5F;
            instrumentTicksText15.Position = elementSize177;
            instrumentTicksText15.Visible = true;
            instrumentMajorTicks8.Labels = instrumentTicksText15;
            elementSize178.Value = 0.25F;
            instrumentMajorTicks8.Length = elementSize178;
            optionalInstrumentProperty15.Visible = true;
            instrumentEndTick15.TickLabel = optionalInstrumentProperty15;
            instrumentEndTick15.Visible = true;
            instrumentMajorTicks8.MaxTick = instrumentEndTick15;
            optionalInstrumentProperty16.Visible = true;
            instrumentEndTick16.TickLabel = optionalInstrumentProperty16;
            instrumentEndTick16.Visible = true;
            instrumentMajorTicks8.MinTick = instrumentEndTick16;
            elementSize179.Value = 0.01F;
            instrumentMajorTicks8.Thickness = elementSize179;
            instrumentMajorTicks8.Visible = true;
            reversibleGaugeScale8.MajorTicks = instrumentMajorTicks8;
            gpBlend62.Blends = gpBlends62;
            gpBlendShape62.Focus = 0.5F;
            gpBlendShape62.Scale = 1F;
            gpBlend62.Shape = gpBlendShape62;
            gpBrush62.Blend = gpBlend62;
            gpBrush62.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor62.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint62.X = 0F;
            gpCenterPoint62.Y = 0F;
            gpCenterColor62.Point = gpCenterPoint62;
            gpGradient62.CenterColor = gpCenterColor62;
            gpGradient62.Colors = gpColors62;
            gpGradient62.Path = gpPoints62;
            gpBrush62.Gradient = gpGradient62;
            gpHatch62.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch62.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush62.Hatch = gpHatch62;
            gpBrush62.InterpolationColors = gpInterpolationColors62;
            instrumentLabeledTicks8.Brush = gpBrush62;
            instrumentLabeledTicks8.Count = ((uint)(3u));
            instrumentTicksText16.Angle = 0F;
            gpBlend63.Blends = gpBlends63;
            gpBlendShape63.Focus = 0.5F;
            gpBlendShape63.Scale = 1F;
            gpBlend63.Shape = gpBlendShape63;
            gpBrush63.Blend = gpBlend63;
            gpBrush63.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor63.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint63.X = 0F;
            gpCenterPoint63.Y = 0F;
            gpCenterColor63.Point = gpCenterPoint63;
            gpGradient63.CenterColor = gpCenterColor63;
            gpGradient63.Colors = gpColors63;
            gpGradient63.Path = gpPoints63;
            gpBrush63.Gradient = gpGradient63;
            gpHatch63.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch63.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush63.Hatch = gpHatch63;
            gpBrush63.InterpolationColors = gpInterpolationColors63;
            controlFont24.Brush = gpBrush63;
            controlFont24.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont24.InternalData")));
            gpBlend64.Blends = gpBlends64;
            gpBlendShape64.Focus = 0.5F;
            gpBlendShape64.Scale = 1F;
            gpBlend64.Shape = gpBlendShape64;
            gpBrush64.Blend = gpBlend64;
            gpBrush64.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor64.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint64.X = 0F;
            gpCenterPoint64.Y = 0F;
            gpCenterColor64.Point = gpCenterPoint64;
            gpGradient64.CenterColor = gpCenterColor64;
            gpGradient64.Colors = gpColors64;
            gpGradient64.Path = gpPoints64;
            gpBrush64.Gradient = gpGradient64;
            gpHatch64.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch64.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush64.Hatch = gpHatch64;
            gpBrush64.InterpolationColors = gpInterpolationColors64;
            gpOptionalMultiPen24.Brush = gpBrush64;
            gpOptionalMultiPen24.Compound = gpPenCompound24;
            gpDashStyle24.CustomDash = gpCustomDash24;
            gpDashStyle24.Offset = 0F;
            gpOptionalMultiPen24.DashStyle = gpDashStyle24;
            gpOptionalMultiPen24.Enabled = false;
            gpOptionalMultiPen24.MiterLimit = 0F;
            gpOptionalMultiPen24.Width = 1F;
            controlFont24.Pen = gpOptionalMultiPen24;
            elementSize180.Value = 0.065F;
            controlFont24.Size = elementSize180;
            instrumentTicksText16.Font = controlFont24;
            elementSize181.Value = 0.45F;
            instrumentTicksText16.Position = elementSize181;
            instrumentTicksText16.Visible = false;
            instrumentLabeledTicks8.Labels = instrumentTicksText16;
            elementSize182.Value = 0.15F;
            instrumentLabeledTicks8.Length = elementSize182;
            elementSize183.Value = 0.005F;
            instrumentLabeledTicks8.Thickness = elementSize183;
            instrumentLabeledTicks8.Visible = true;
            reversibleGaugeScale8.MinorTicks = instrumentLabeledTicks8;
            elementSize184.Value = 0.25F;
            reversibleGaugeScale8.Position = elementSize184;
            scalePrecision8.FixedPrecision = false;
            scalePrecision8.NumberDigits = ((uint)(2u));
            reversibleGaugeScale8.Precision = scalePrecision8;
            reversibleGaugeScale8.Reversed = true;
            this.gaugePortTrim.Scale = reversibleGaugeScale8;
            this.gaugePortTrim.Size = new System.Drawing.Size(158, 424);
            this.gaugePortTrim.TabIndex = 108;
            this.gaugePortTrim.TabStop = false;
            this.gaugePortTrim.Text = "linearGauge2";
            this.gaugePortTrim.Value = 100D;
            // 
            // label36
            // 
            this.label36.Font = new System.Drawing.Font("Arial", 14F);
            this.label36.ForeColor = System.Drawing.Color.White;
            this.label36.Location = new System.Drawing.Point(168, 6);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(479, 25);
            this.label36.TabIndex = 109;
            this.label36.Text = "TRIM CONTROL";
            this.label36.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Arial", 14F);
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(19, 91);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(199, 25);
            this.label1.TabIndex = 110;
            this.label1.Text = "PORT";
            this.label1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label2
            // 
            this.label2.Font = new System.Drawing.Font("Arial", 14F);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(582, 91);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(199, 25);
            this.label2.TabIndex = 111;
            this.label2.Text = "STBD";
            this.label2.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label5
            // 
            this.label5.Font = new System.Drawing.Font("Arial", 36F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(264, 232);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(102, 46);
            this.label5.TabIndex = 112;
            this.label5.Text = "--";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label3
            // 
            this.label3.Font = new System.Drawing.Font("Arial", 36F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(436, 232);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(102, 46);
            this.label3.TabIndex = 113;
            this.label3.Text = "--";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Black;
            this.panel1.Location = new System.Drawing.Point(262, 75);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(31, 360);
            this.panel1.TabIndex = 114;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.Black;
            this.panel2.Location = new System.Drawing.Point(513, 77);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(33, 360);
            this.panel2.TabIndex = 115;
            // 
            // label4
            // 
            this.label4.BackColor = System.Drawing.Color.Black;
            this.label4.Font = new System.Drawing.Font("Arial", 14F);
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(257, 420);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(70, 25);
            this.label4.TabIndex = 116;
            this.label4.Text = "100%";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label6
            // 
            this.label6.BackColor = System.Drawing.Color.Black;
            this.label6.Font = new System.Drawing.Font("Arial", 14F);
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(273, 243);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(54, 25);
            this.label6.TabIndex = 117;
            this.label6.Text = "50%";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label7
            // 
            this.label7.BackColor = System.Drawing.Color.Black;
            this.label7.Font = new System.Drawing.Font("Arial", 14F);
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(273, 154);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(54, 25);
            this.label7.TabIndex = 118;
            this.label7.Text = "25%";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label8
            // 
            this.label8.BackColor = System.Drawing.Color.Black;
            this.label8.Font = new System.Drawing.Font("Arial", 14F);
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(273, 331);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(54, 25);
            this.label8.TabIndex = 119;
            this.label8.Text = "75%";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label9
            // 
            this.label9.BackColor = System.Drawing.Color.Black;
            this.label9.Font = new System.Drawing.Font("Arial", 14F);
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(273, 66);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(54, 25);
            this.label9.TabIndex = 120;
            this.label9.Text = "0%";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label10
            // 
            this.label10.BackColor = System.Drawing.Color.Black;
            this.label10.Font = new System.Drawing.Font("Arial", 14F);
            this.label10.ForeColor = System.Drawing.Color.White;
            this.label10.Location = new System.Drawing.Point(480, 67);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(54, 25);
            this.label10.TabIndex = 125;
            this.label10.Text = "0%";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label11
            // 
            this.label11.BackColor = System.Drawing.Color.Black;
            this.label11.Font = new System.Drawing.Font("Arial", 14F);
            this.label11.ForeColor = System.Drawing.Color.White;
            this.label11.Location = new System.Drawing.Point(480, 332);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(54, 25);
            this.label11.TabIndex = 124;
            this.label11.Text = "75%";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label12
            // 
            this.label12.BackColor = System.Drawing.Color.Black;
            this.label12.Font = new System.Drawing.Font("Arial", 14F);
            this.label12.ForeColor = System.Drawing.Color.White;
            this.label12.Location = new System.Drawing.Point(480, 155);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(54, 25);
            this.label12.TabIndex = 123;
            this.label12.Text = "25%";
            this.label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label13
            // 
            this.label13.BackColor = System.Drawing.Color.Black;
            this.label13.Font = new System.Drawing.Font("Arial", 14F);
            this.label13.ForeColor = System.Drawing.Color.White;
            this.label13.Location = new System.Drawing.Point(480, 244);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(54, 25);
            this.label13.TabIndex = 122;
            this.label13.Text = "50%";
            this.label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label14
            // 
            this.label14.BackColor = System.Drawing.Color.Black;
            this.label14.Font = new System.Drawing.Font("Arial", 14F);
            this.label14.ForeColor = System.Drawing.Color.White;
            this.label14.Location = new System.Drawing.Point(480, 421);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(70, 25);
            this.label14.TabIndex = 121;
            this.label14.Text = "100%";
            this.label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // checkBox1
            // 
            this.checkBox1.AutoSize = true;
            this.checkBox1.Checked = true;
            this.checkBox1.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox1.Font = new System.Drawing.Font("Arial", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.checkBox1.ForeColor = System.Drawing.Color.White;
            this.checkBox1.Location = new System.Drawing.Point(604, 23);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(167, 26);
            this.checkBox1.TabIndex = 127;
            this.checkBox1.Text = "SYNCHRONIZE";
            this.checkBox1.UseVisualStyleBackColor = true;
            // 
            // dashboardButton2
            // 
            this.dashboardButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton2.BackgroundImage")));
            this.dashboardButton2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.dashboardButton2.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.dashboardButton2.FlatAppearance.BorderSize = 0;
            this.dashboardButton2.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton2.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dashboardButton2.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardButton2.ForeColor = System.Drawing.Color.White;
            this.dashboardButton2.Function = "PORT TRIM DOWN";
            this.dashboardButton2.Location = new System.Drawing.Point(19, 248);
            this.dashboardButton2.MvecAddress = ((byte)(177));
            this.dashboardButton2.MvecFuseNumber = ((byte)(8));
            this.dashboardButton2.MvecGrid = ((byte)(0));
            this.dashboardButton2.MvecRelayNumber = ((byte)(5));
            this.dashboardButton2.Name = "dashboardButton2";
            this.dashboardButton2.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton2.OffStateBackImage")));
            this.dashboardButton2.OffStateForeColor = System.Drawing.Color.White;
            this.dashboardButton2.OffStateText = "BOW\r\nDOWN";
            this.dashboardButton2.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton2.OnStateBackImage")));
            this.dashboardButton2.OnStateForeColor = System.Drawing.Color.White;
            this.dashboardButton2.OnStateText = "BOW\r\nDOWN";
            this.dashboardButton2.Size = new System.Drawing.Size(199, 111);
            this.dashboardButton2.State = false;
            this.dashboardButton2.TabIndex = 107;
            this.dashboardButton2.Text = "BOW\r\nDOWN";
            this.dashboardButton2.UseVisualStyleBackColor = true;
            this.dashboardButton2.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.dashboardButton2_NewCommand);
            // 
            // dashboardButton3
            // 
            this.dashboardButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton3.BackgroundImage")));
            this.dashboardButton3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.dashboardButton3.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.dashboardButton3.FlatAppearance.BorderSize = 0;
            this.dashboardButton3.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton3.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dashboardButton3.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardButton3.ForeColor = System.Drawing.Color.White;
            this.dashboardButton3.Function = "PORT TRIM UP";
            this.dashboardButton3.Location = new System.Drawing.Point(19, 131);
            this.dashboardButton3.MvecAddress = ((byte)(177));
            this.dashboardButton3.MvecFuseNumber = ((byte)(4));
            this.dashboardButton3.MvecGrid = ((byte)(0));
            this.dashboardButton3.MvecRelayNumber = ((byte)(2));
            this.dashboardButton3.Name = "dashboardButton3";
            this.dashboardButton3.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton3.OffStateBackImage")));
            this.dashboardButton3.OffStateForeColor = System.Drawing.Color.White;
            this.dashboardButton3.OffStateText = "BOW\r\nUP";
            this.dashboardButton3.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton3.OnStateBackImage")));
            this.dashboardButton3.OnStateForeColor = System.Drawing.Color.White;
            this.dashboardButton3.OnStateText = "BOW\r\nUP";
            this.dashboardButton3.Size = new System.Drawing.Size(199, 111);
            this.dashboardButton3.State = false;
            this.dashboardButton3.TabIndex = 106;
            this.dashboardButton3.Text = "BOW\r\nUP";
            this.dashboardButton3.UseVisualStyleBackColor = true;
            this.dashboardButton3.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.dashboardButton3_NewCommand);
            this.dashboardButton3.Click += new System.EventHandler(this.dashboardButton3_Click);
            // 
            // dashboardButton1
            // 
            this.dashboardButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton1.BackgroundImage")));
            this.dashboardButton1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.dashboardButton1.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.dashboardButton1.FlatAppearance.BorderSize = 0;
            this.dashboardButton1.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dashboardButton1.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardButton1.ForeColor = System.Drawing.Color.White;
            this.dashboardButton1.Function = "STBD TRIM DOWN";
            this.dashboardButton1.Location = new System.Drawing.Point(582, 248);
            this.dashboardButton1.MvecAddress = ((byte)(177));
            this.dashboardButton1.MvecFuseNumber = ((byte)(2));
            this.dashboardButton1.MvecGrid = ((byte)(0));
            this.dashboardButton1.MvecRelayNumber = ((byte)(4));
            this.dashboardButton1.Name = "dashboardButton1";
            this.dashboardButton1.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton1.OffStateBackImage")));
            this.dashboardButton1.OffStateForeColor = System.Drawing.Color.White;
            this.dashboardButton1.OffStateText = "BOW\r\nDOWN";
            this.dashboardButton1.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton1.OnStateBackImage")));
            this.dashboardButton1.OnStateForeColor = System.Drawing.Color.White;
            this.dashboardButton1.OnStateText = "BOW\r\nDOWN";
            this.dashboardButton1.Size = new System.Drawing.Size(199, 111);
            this.dashboardButton1.State = false;
            this.dashboardButton1.TabIndex = 105;
            this.dashboardButton1.Text = "BOW\r\nDOWN";
            this.dashboardButton1.UseVisualStyleBackColor = true;
            this.dashboardButton1.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.dashboardButton1_NewCommand);
            // 
            // dashboardButton7
            // 
            this.dashboardButton7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton7.BackgroundImage")));
            this.dashboardButton7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.dashboardButton7.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.dashboardButton7.FlatAppearance.BorderSize = 0;
            this.dashboardButton7.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton7.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton7.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dashboardButton7.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardButton7.ForeColor = System.Drawing.Color.White;
            this.dashboardButton7.Function = "STBD TRIM UP";
            this.dashboardButton7.Location = new System.Drawing.Point(582, 131);
            this.dashboardButton7.MvecAddress = ((byte)(177));
            this.dashboardButton7.MvecFuseNumber = ((byte)(1));
            this.dashboardButton7.MvecGrid = ((byte)(0));
            this.dashboardButton7.MvecRelayNumber = ((byte)(1));
            this.dashboardButton7.Name = "dashboardButton7";
            this.dashboardButton7.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton7.OffStateBackImage")));
            this.dashboardButton7.OffStateForeColor = System.Drawing.Color.White;
            this.dashboardButton7.OffStateText = "BOW\r\nUP";
            this.dashboardButton7.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton7.OnStateBackImage")));
            this.dashboardButton7.OnStateForeColor = System.Drawing.Color.White;
            this.dashboardButton7.OnStateText = "BOW\r\nUP";
            this.dashboardButton7.Size = new System.Drawing.Size(199, 111);
            this.dashboardButton7.State = false;
            this.dashboardButton7.TabIndex = 104;
            this.dashboardButton7.Text = "BOW\r\nUP";
            this.dashboardButton7.UseVisualStyleBackColor = true;
            this.dashboardButton7.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.dashboardButton7_NewCommand);
            // 
            // btnConfigNmea2000
            // 
            this.btnConfigNmea2000.BackgroundImage = global::WhatTheHelmRuntime.Properties.Resources.BlackButton;
            this.btnConfigNmea2000.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnConfigNmea2000.FlatAppearance.BorderSize = 0;
            this.btnConfigNmea2000.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnConfigNmea2000.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnConfigNmea2000.ForeColor = System.Drawing.Color.White;
            this.btnConfigNmea2000.Location = new System.Drawing.Point(23, 33);
            this.btnConfigNmea2000.Margin = new System.Windows.Forms.Padding(2);
            this.btnConfigNmea2000.Name = "btnConfigNmea2000";
            this.btnConfigNmea2000.Size = new System.Drawing.Size(157, 53);
            this.btnConfigNmea2000.TabIndex = 154;
            this.btnConfigNmea2000.TabStop = false;
            this.btnConfigNmea2000.Text = "NMEA 2000\r\nCONFIGURATION";
            this.btnConfigNmea2000.UseVisualStyleBackColor = true;
            this.btnConfigNmea2000.Click += new System.EventHandler(this.btnConfigNmea2000_Click);
            // 
            // TrimControl
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.Controls.Add(this.btnConfigNmea2000);
            this.Controls.Add(this.checkBox1);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.gaugePortTrim);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label36);
            this.Controls.Add(this.dashboardButton2);
            this.Controls.Add(this.dashboardButton3);
            this.Controls.Add(this.dashboardButton1);
            this.Controls.Add(this.dashboardButton7);
            this.Controls.Add(this.gaugeStbdTrim);
            this.Controls.Add(this.label3);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "TrimControl";
            this.Text = "TrimControl";
            ((System.ComponentModel.ISupportInitialize)(this.gaugeStbdTrim)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gaugePortTrim)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Mitov.InstrumentLab.LinearGauge gaugeStbdTrim;
        private BoatFormsLib.CustomUserControls.DashboardButton dashboardButton7;
        private BoatFormsLib.CustomUserControls.DashboardButton dashboardButton1;
        private BoatFormsLib.CustomUserControls.DashboardButton dashboardButton2;
        private BoatFormsLib.CustomUserControls.DashboardButton dashboardButton3;
        private Mitov.InstrumentLab.LinearGauge gaugePortTrim;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.CheckBox checkBox1;
        private System.Windows.Forms.Button btnConfigNmea2000;
    }
}