namespace WhatTheHelmRuntime
{
    partial class TrimControl
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Mitov.BasicLab.ControlBackground controlBackground1 = new Mitov.BasicLab.ControlBackground();
            Mitov.BasicLab.RectControlBorder rectControlBorder1 = new Mitov.BasicLab.RectControlBorder();
            Mitov.BasicLab.ControlInnerBevel controlInnerBevel1 = new Mitov.BasicLab.ControlInnerBevel();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TrimControl));
            Mitov.BasicLab.ElementSize elementSize1 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ControlBevel controlBevel1 = new Mitov.BasicLab.ControlBevel();
            Mitov.BasicLab.ElementSize elementSize2 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize3 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize4 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.VerticalCaption verticalCaption1 = new Mitov.BasicLab.VerticalCaption();
            Mitov.BasicLab.ControlFont controlFont1 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush1 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend1 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends1 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape1 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient1 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor1 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint1 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors1 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints1 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch1 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors1 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen1 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush2 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend2 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends2 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape2 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient2 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor2 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint2 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors2 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints2 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch2 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors2 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound1 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle1 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash1 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize5 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets1 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize1 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize2 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.InstrumentLab.Glass glass1 = new Mitov.InstrumentLab.Glass();
            Mitov.InstrumentLab.OptionalLinearGaugeHand optionalLinearGaugeHand1 = new Mitov.InstrumentLab.OptionalLinearGaugeHand();
            Mitov.InstrumentLab.HandAnimation handAnimation1 = new Mitov.InstrumentLab.HandAnimation();
            Mitov.BasicLab.ElementSize elementSize6 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ElementShadow elementShadow1 = new Mitov.InstrumentLab.ElementShadow();
            Mitov.BasicLab.ElementSize elementSize7 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize8 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize9 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize10 = new Mitov.BasicLab.ElementSize();
            OpenWire.Proxy.SinkPin sinkPin1 = new OpenWire.Proxy.SinkPin();
            Mitov.InstrumentLab.LinearGaugeRail linearGaugeRail1 = new Mitov.InstrumentLab.LinearGaugeRail();
            Mitov.BasicLab.ElementSize elementSize11 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets2 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize3 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize4 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementSize elementSize12 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.AnalogGaugeScaleRanges analogGaugeScaleRanges1 = new Mitov.InstrumentLab.AnalogGaugeScaleRanges();
            Mitov.BasicLab.ElementSize elementSize13 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize14 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.Rotation rotation1 = new Mitov.InstrumentLab.Rotation();
            Mitov.InstrumentLab.ReversibleGaugeScale reversibleGaugeScale1 = new Mitov.InstrumentLab.ReversibleGaugeScale();
            Mitov.InstrumentLab.InstrumentMajorTicks instrumentMajorTicks1 = new Mitov.InstrumentLab.InstrumentMajorTicks();
            Mitov.BasicLab.GPBrush gpBrush3 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend3 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends3 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape3 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient3 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor3 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint3 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors3 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints3 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch3 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors3 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText1 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont2 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush4 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend4 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends4 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape4 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient4 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor4 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint4 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors4 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints4 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch4 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors4 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen2 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush5 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend5 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends5 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape5 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient5 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor5 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint5 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors5 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints5 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch5 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors5 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound2 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle2 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash2 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize15 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize16 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize17 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick1 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty1 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick2 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty2 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.BasicLab.ElementSize elementSize18 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentLabeledTicks instrumentLabeledTicks1 = new Mitov.InstrumentLab.InstrumentLabeledTicks();
            Mitov.BasicLab.GPBrush gpBrush6 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend6 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends6 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape6 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient6 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor6 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint6 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors6 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints6 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch6 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors6 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText2 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont3 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush7 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend7 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends7 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape7 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient7 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor7 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint7 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors7 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints7 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch7 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors7 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen3 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush8 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend8 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends8 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape8 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient8 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor8 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint8 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors8 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints8 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch8 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors8 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound3 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle3 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash3 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize19 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize20 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize21 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize22 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize23 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ScalePrecision scalePrecision1 = new Mitov.InstrumentLab.ScalePrecision();
            Mitov.BasicLab.ControlBackground controlBackground2 = new Mitov.BasicLab.ControlBackground();
            Mitov.BasicLab.RectControlBorder rectControlBorder2 = new Mitov.BasicLab.RectControlBorder();
            Mitov.BasicLab.ControlInnerBevel controlInnerBevel2 = new Mitov.BasicLab.ControlInnerBevel();
            Mitov.BasicLab.ElementSize elementSize24 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ControlBevel controlBevel2 = new Mitov.BasicLab.ControlBevel();
            Mitov.BasicLab.ElementSize elementSize25 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize26 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize27 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.VerticalCaption verticalCaption2 = new Mitov.BasicLab.VerticalCaption();
            Mitov.BasicLab.ControlFont controlFont4 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush9 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend9 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends9 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape9 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient9 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor9 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint9 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors9 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints9 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch9 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors9 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen4 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush10 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend10 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends10 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape10 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient10 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor10 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint10 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors10 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints10 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch10 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors10 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound4 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle4 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash4 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize28 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets3 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize5 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize6 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.InstrumentLab.Glass glass2 = new Mitov.InstrumentLab.Glass();
            Mitov.InstrumentLab.OptionalLinearGaugeHand optionalLinearGaugeHand2 = new Mitov.InstrumentLab.OptionalLinearGaugeHand();
            Mitov.InstrumentLab.HandAnimation handAnimation2 = new Mitov.InstrumentLab.HandAnimation();
            Mitov.BasicLab.ElementSize elementSize29 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ElementShadow elementShadow2 = new Mitov.InstrumentLab.ElementShadow();
            Mitov.BasicLab.ElementSize elementSize30 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize31 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize32 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize33 = new Mitov.BasicLab.ElementSize();
            OpenWire.Proxy.SinkPin sinkPin2 = new OpenWire.Proxy.SinkPin();
            Mitov.InstrumentLab.LinearGaugeRail linearGaugeRail2 = new Mitov.InstrumentLab.LinearGaugeRail();
            Mitov.BasicLab.ElementSize elementSize34 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementOffsets elementOffsets4 = new Mitov.BasicLab.ElementOffsets();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize7 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementOffsetSize elementOffsetSize8 = new Mitov.BasicLab.ElementOffsetSize();
            Mitov.BasicLab.ElementSize elementSize35 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.AnalogGaugeScaleRanges analogGaugeScaleRanges2 = new Mitov.InstrumentLab.AnalogGaugeScaleRanges();
            Mitov.BasicLab.ElementSize elementSize36 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize37 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.Rotation rotation2 = new Mitov.InstrumentLab.Rotation();
            Mitov.InstrumentLab.ReversibleGaugeScale reversibleGaugeScale2 = new Mitov.InstrumentLab.ReversibleGaugeScale();
            Mitov.InstrumentLab.InstrumentMajorTicks instrumentMajorTicks2 = new Mitov.InstrumentLab.InstrumentMajorTicks();
            Mitov.BasicLab.GPBrush gpBrush11 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend11 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends11 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape11 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient11 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor11 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint11 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors11 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints11 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch11 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors11 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText3 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont5 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush12 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend12 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends12 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape12 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient12 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor12 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint12 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors12 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints12 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch12 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors12 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen5 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush13 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend13 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends13 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape13 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient13 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor13 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint13 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors13 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints13 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch13 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors13 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound5 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle5 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash5 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize38 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize39 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize40 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick3 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty3 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.InstrumentLab.InstrumentEndTick instrumentEndTick4 = new Mitov.InstrumentLab.InstrumentEndTick();
            Mitov.BasicLab.OptionalInstrumentProperty optionalInstrumentProperty4 = new Mitov.BasicLab.OptionalInstrumentProperty();
            Mitov.BasicLab.ElementSize elementSize41 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.InstrumentLabeledTicks instrumentLabeledTicks2 = new Mitov.InstrumentLab.InstrumentLabeledTicks();
            Mitov.BasicLab.GPBrush gpBrush14 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend14 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends14 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape14 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient14 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor14 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint14 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors14 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints14 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch14 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors14 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.InstrumentLab.InstrumentTicksText instrumentTicksText4 = new Mitov.InstrumentLab.InstrumentTicksText();
            Mitov.BasicLab.ControlFont controlFont6 = new Mitov.BasicLab.ControlFont();
            Mitov.BasicLab.GPBrush gpBrush15 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend15 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends15 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape15 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient15 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor15 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint15 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors15 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints15 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch15 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors15 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPOptionalMultiPen gpOptionalMultiPen6 = new Mitov.BasicLab.GPOptionalMultiPen();
            Mitov.BasicLab.GPBrush gpBrush16 = new Mitov.BasicLab.GPBrush();
            Mitov.BasicLab.GPBlend gpBlend16 = new Mitov.BasicLab.GPBlend();
            Mitov.BasicLab.GPBlends gpBlends16 = new Mitov.BasicLab.GPBlends();
            Mitov.BasicLab.GPBlendShape gpBlendShape16 = new Mitov.BasicLab.GPBlendShape();
            Mitov.BasicLab.GPGradient gpGradient16 = new Mitov.BasicLab.GPGradient();
            Mitov.BasicLab.GPCenterColor gpCenterColor16 = new Mitov.BasicLab.GPCenterColor();
            Mitov.BasicLab.GPCenterPoint gpCenterPoint16 = new Mitov.BasicLab.GPCenterPoint();
            Mitov.BasicLab.GPColors gpColors16 = new Mitov.BasicLab.GPColors();
            Mitov.BasicLab.GPPoints gpPoints16 = new Mitov.BasicLab.GPPoints();
            Mitov.BasicLab.GPHatch gpHatch16 = new Mitov.BasicLab.GPHatch();
            Mitov.BasicLab.GPInterpolationColors gpInterpolationColors16 = new Mitov.BasicLab.GPInterpolationColors();
            Mitov.BasicLab.GPPenCompound gpPenCompound6 = new Mitov.BasicLab.GPPenCompound();
            Mitov.BasicLab.GPDashStyle gpDashStyle6 = new Mitov.BasicLab.GPDashStyle();
            Mitov.BasicLab.GPCustomDash gpCustomDash6 = new Mitov.BasicLab.GPCustomDash();
            Mitov.BasicLab.ElementSize elementSize42 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize43 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize44 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize45 = new Mitov.BasicLab.ElementSize();
            Mitov.BasicLab.ElementSize elementSize46 = new Mitov.BasicLab.ElementSize();
            Mitov.InstrumentLab.ScalePrecision scalePrecision2 = new Mitov.InstrumentLab.ScalePrecision();
            this.gaugeStbdTrim = new Mitov.InstrumentLab.LinearGauge(this.components);
            this.gaugePortTrim = new Mitov.InstrumentLab.LinearGauge(this.components);
            this.label36 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.label4 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.dashboardButton2 = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.dashboardButton3 = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.dashboardButton1 = new BoatFormsLib.CustomUserControls.DashboardButton();
            this.dashboardButton7 = new BoatFormsLib.CustomUserControls.DashboardButton();
            ((System.ComponentModel.ISupportInitialize)(this.gaugeStbdTrim)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gaugePortTrim)).BeginInit();
            this.SuspendLayout();
            // 
            // gaugeStbdTrim
            // 
            controlBackground1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.gaugeStbdTrim.Background = controlBackground1;
            controlInnerBevel1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlInnerBevel1.InternalData")));
            elementSize1.Value = 0.05F;
            controlInnerBevel1.Width = elementSize1;
            rectControlBorder1.BevelInner = controlInnerBevel1;
            elementSize2.Value = 0.05F;
            controlBevel1.Width = elementSize2;
            rectControlBorder1.BevelOuter = controlBevel1;
            rectControlBorder1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            elementSize3.Value = 0.2F;
            rectControlBorder1.CornerRadius = elementSize3;
            rectControlBorder1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("rectControlBorder1.InternalData")));
            elementSize4.Value = 0F;
            rectControlBorder1.Width = elementSize4;
            this.gaugeStbdTrim.Border = rectControlBorder1;
            verticalCaption1.Angle = 0F;
            gpBlend1.Blends = gpBlends1;
            gpBlendShape1.Focus = 0.5F;
            gpBlendShape1.Scale = 1F;
            gpBlend1.Shape = gpBlendShape1;
            gpBrush1.Blend = gpBlend1;
            gpBrush1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint1.X = 0F;
            gpCenterPoint1.Y = 0F;
            gpCenterColor1.Point = gpCenterPoint1;
            gpGradient1.CenterColor = gpCenterColor1;
            gpGradient1.Colors = gpColors1;
            gpGradient1.Path = gpPoints1;
            gpBrush1.Gradient = gpGradient1;
            gpHatch1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch1.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush1.Hatch = gpHatch1;
            gpBrush1.InterpolationColors = gpInterpolationColors1;
            controlFont1.Brush = gpBrush1;
            controlFont1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont1.InternalData")));
            gpBlend2.Blends = gpBlends2;
            gpBlendShape2.Focus = 0.5F;
            gpBlendShape2.Scale = 1F;
            gpBlend2.Shape = gpBlendShape2;
            gpBrush2.Blend = gpBlend2;
            gpBrush2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint2.X = 0F;
            gpCenterPoint2.Y = 0F;
            gpCenterColor2.Point = gpCenterPoint2;
            gpGradient2.CenterColor = gpCenterColor2;
            gpGradient2.Colors = gpColors2;
            gpGradient2.Path = gpPoints2;
            gpBrush2.Gradient = gpGradient2;
            gpHatch2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch2.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush2.Hatch = gpHatch2;
            gpBrush2.InterpolationColors = gpInterpolationColors2;
            gpOptionalMultiPen1.Brush = gpBrush2;
            gpOptionalMultiPen1.Compound = gpPenCompound1;
            gpDashStyle1.CustomDash = gpCustomDash1;
            gpDashStyle1.Offset = 0F;
            gpOptionalMultiPen1.DashStyle = gpDashStyle1;
            gpOptionalMultiPen1.Enabled = false;
            gpOptionalMultiPen1.MiterLimit = 0F;
            gpOptionalMultiPen1.Width = 1F;
            controlFont1.Pen = gpOptionalMultiPen1;
            elementSize5.Value = 0.25F;
            controlFont1.Size = elementSize5;
            verticalCaption1.Font = controlFont1;
            elementOffsetSize1.Value = 0.8F;
            elementOffsets1.X = elementOffsetSize1;
            elementOffsetSize2.Value = 0F;
            elementOffsets1.Y = elementOffsetSize2;
            verticalCaption1.Position = elementOffsets1;
            this.gaugeStbdTrim.Caption = verticalCaption1;
            this.gaugeStbdTrim.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.gaugeStbdTrim.Curved = false;
            glass1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            glass1.Visible = false;
            this.gaugeStbdTrim.Glass = glass1;
            handAnimation1.Acceleration = 0.015F;
            handAnimation1.Resistance = 0.16F;
            optionalLinearGaugeHand1.Animation = handAnimation1;
            optionalLinearGaugeHand1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            elementSize6.Value = 0.33F;
            optionalLinearGaugeHand1.Length = elementSize6;
            optionalLinearGaugeHand1.Shadow = elementShadow1;
            elementSize7.Value = 0.15F;
            optionalLinearGaugeHand1.TailIndentSize = elementSize7;
            elementSize8.Value = 0.65F;
            optionalLinearGaugeHand1.TipLength = elementSize8;
            elementSize9.Value = 0.2F;
            optionalLinearGaugeHand1.TipWidth = elementSize9;
            elementSize10.Value = 0.03F;
            optionalLinearGaugeHand1.Width = elementSize10;
            this.gaugeStbdTrim.Hand = optionalLinearGaugeHand1;
            this.gaugeStbdTrim.InputPin = sinkPin1;
            this.gaugeStbdTrim.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("gaugeStbdTrim.InternalData")));
            this.gaugeStbdTrim.Location = new System.Drawing.Point(409, 44);
            this.gaugeStbdTrim.Max = 0D;
            this.gaugeStbdTrim.Min = 100D;
            this.gaugeStbdTrim.Name = "gaugeStbdTrim";
            elementSize11.Value = 0.9F;
            linearGaugeRail1.Length = elementSize11;
            elementOffsetSize3.Value = 0.1F;
            elementOffsets2.X = elementOffsetSize3;
            elementOffsetSize4.Value = 0F;
            elementOffsets2.Y = elementOffsetSize4;
            linearGaugeRail1.Position = elementOffsets2;
            elementSize12.Value = 0.08F;
            linearGaugeRail1.Width = elementSize12;
            this.gaugeStbdTrim.Rail = linearGaugeRail1;
            analogGaugeScaleRanges1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            elementSize13.Value = 0.2F;
            analogGaugeScaleRanges1.Position = elementSize13;
            elementSize14.Value = 0.05F;
            analogGaugeScaleRanges1.Width = elementSize14;
            this.gaugeStbdTrim.Ranges = analogGaugeScaleRanges1;
            rotation1.Angle = 0F;
            rotation1.Width = 0.7F;
            this.gaugeStbdTrim.Rotation = rotation1;
            gpBlend3.Blends = gpBlends3;
            gpBlendShape3.Focus = 0.5F;
            gpBlendShape3.Scale = 1F;
            gpBlend3.Shape = gpBlendShape3;
            gpBrush3.Blend = gpBlend3;
            gpBrush3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint3.X = 0F;
            gpCenterPoint3.Y = 0F;
            gpCenterColor3.Point = gpCenterPoint3;
            gpGradient3.CenterColor = gpCenterColor3;
            gpGradient3.Colors = gpColors3;
            gpGradient3.Path = gpPoints3;
            gpBrush3.Gradient = gpGradient3;
            gpHatch3.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch3.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush3.Hatch = gpHatch3;
            gpBrush3.InterpolationColors = gpInterpolationColors3;
            instrumentMajorTicks1.Brush = gpBrush3;
            instrumentMajorTicks1.Count = ((uint)(5u));
            instrumentTicksText1.Angle = 0F;
            gpBlend4.Blends = gpBlends4;
            gpBlendShape4.Focus = 0.5F;
            gpBlendShape4.Scale = 1F;
            gpBlend4.Shape = gpBlendShape4;
            gpBrush4.Blend = gpBlend4;
            gpBrush4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint4.X = 0F;
            gpCenterPoint4.Y = 0F;
            gpCenterColor4.Point = gpCenterPoint4;
            gpGradient4.CenterColor = gpCenterColor4;
            gpGradient4.Colors = gpColors4;
            gpGradient4.Path = gpPoints4;
            gpBrush4.Gradient = gpGradient4;
            gpHatch4.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch4.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush4.Hatch = gpHatch4;
            gpBrush4.InterpolationColors = gpInterpolationColors4;
            controlFont2.Brush = gpBrush4;
            controlFont2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont2.InternalData")));
            gpBlend5.Blends = gpBlends5;
            gpBlendShape5.Focus = 0.5F;
            gpBlendShape5.Scale = 1F;
            gpBlend5.Shape = gpBlendShape5;
            gpBrush5.Blend = gpBlend5;
            gpBrush5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint5.X = 0F;
            gpCenterPoint5.Y = 0F;
            gpCenterColor5.Point = gpCenterPoint5;
            gpGradient5.CenterColor = gpCenterColor5;
            gpGradient5.Colors = gpColors5;
            gpGradient5.Path = gpPoints5;
            gpBrush5.Gradient = gpGradient5;
            gpHatch5.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch5.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush5.Hatch = gpHatch5;
            gpBrush5.InterpolationColors = gpInterpolationColors5;
            gpOptionalMultiPen2.Brush = gpBrush5;
            gpOptionalMultiPen2.Compound = gpPenCompound2;
            gpDashStyle2.CustomDash = gpCustomDash2;
            gpDashStyle2.Offset = 0F;
            gpOptionalMultiPen2.DashStyle = gpDashStyle2;
            gpOptionalMultiPen2.Enabled = false;
            gpOptionalMultiPen2.MiterLimit = 0F;
            gpOptionalMultiPen2.Width = 1F;
            controlFont2.Pen = gpOptionalMultiPen2;
            elementSize15.Value = 0.09F;
            controlFont2.Size = elementSize15;
            instrumentTicksText1.Font = controlFont2;
            elementSize16.Value = 0.5F;
            instrumentTicksText1.Position = elementSize16;
            instrumentTicksText1.Visible = true;
            instrumentMajorTicks1.Labels = instrumentTicksText1;
            elementSize17.Value = 0.25F;
            instrumentMajorTicks1.Length = elementSize17;
            optionalInstrumentProperty1.Visible = true;
            instrumentEndTick1.TickLabel = optionalInstrumentProperty1;
            instrumentEndTick1.Visible = true;
            instrumentMajorTicks1.MaxTick = instrumentEndTick1;
            optionalInstrumentProperty2.Visible = true;
            instrumentEndTick2.TickLabel = optionalInstrumentProperty2;
            instrumentEndTick2.Visible = true;
            instrumentMajorTicks1.MinTick = instrumentEndTick2;
            elementSize18.Value = 0.01F;
            instrumentMajorTicks1.Thickness = elementSize18;
            instrumentMajorTicks1.Visible = true;
            reversibleGaugeScale1.MajorTicks = instrumentMajorTicks1;
            gpBlend6.Blends = gpBlends6;
            gpBlendShape6.Focus = 0.5F;
            gpBlendShape6.Scale = 1F;
            gpBlend6.Shape = gpBlendShape6;
            gpBrush6.Blend = gpBlend6;
            gpBrush6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint6.X = 0F;
            gpCenterPoint6.Y = 0F;
            gpCenterColor6.Point = gpCenterPoint6;
            gpGradient6.CenterColor = gpCenterColor6;
            gpGradient6.Colors = gpColors6;
            gpGradient6.Path = gpPoints6;
            gpBrush6.Gradient = gpGradient6;
            gpHatch6.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch6.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush6.Hatch = gpHatch6;
            gpBrush6.InterpolationColors = gpInterpolationColors6;
            instrumentLabeledTicks1.Brush = gpBrush6;
            instrumentLabeledTicks1.Count = ((uint)(3u));
            instrumentTicksText2.Angle = 0F;
            gpBlend7.Blends = gpBlends7;
            gpBlendShape7.Focus = 0.5F;
            gpBlendShape7.Scale = 1F;
            gpBlend7.Shape = gpBlendShape7;
            gpBrush7.Blend = gpBlend7;
            gpBrush7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint7.X = 0F;
            gpCenterPoint7.Y = 0F;
            gpCenterColor7.Point = gpCenterPoint7;
            gpGradient7.CenterColor = gpCenterColor7;
            gpGradient7.Colors = gpColors7;
            gpGradient7.Path = gpPoints7;
            gpBrush7.Gradient = gpGradient7;
            gpHatch7.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch7.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush7.Hatch = gpHatch7;
            gpBrush7.InterpolationColors = gpInterpolationColors7;
            controlFont3.Brush = gpBrush7;
            controlFont3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont3.InternalData")));
            gpBlend8.Blends = gpBlends8;
            gpBlendShape8.Focus = 0.5F;
            gpBlendShape8.Scale = 1F;
            gpBlend8.Shape = gpBlendShape8;
            gpBrush8.Blend = gpBlend8;
            gpBrush8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint8.X = 0F;
            gpCenterPoint8.Y = 0F;
            gpCenterColor8.Point = gpCenterPoint8;
            gpGradient8.CenterColor = gpCenterColor8;
            gpGradient8.Colors = gpColors8;
            gpGradient8.Path = gpPoints8;
            gpBrush8.Gradient = gpGradient8;
            gpHatch8.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch8.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush8.Hatch = gpHatch8;
            gpBrush8.InterpolationColors = gpInterpolationColors8;
            gpOptionalMultiPen3.Brush = gpBrush8;
            gpOptionalMultiPen3.Compound = gpPenCompound3;
            gpDashStyle3.CustomDash = gpCustomDash3;
            gpDashStyle3.Offset = 0F;
            gpOptionalMultiPen3.DashStyle = gpDashStyle3;
            gpOptionalMultiPen3.Enabled = false;
            gpOptionalMultiPen3.MiterLimit = 0F;
            gpOptionalMultiPen3.Width = 1F;
            controlFont3.Pen = gpOptionalMultiPen3;
            elementSize19.Value = 0.065F;
            controlFont3.Size = elementSize19;
            instrumentTicksText2.Font = controlFont3;
            elementSize20.Value = 0.45F;
            instrumentTicksText2.Position = elementSize20;
            instrumentTicksText2.Visible = false;
            instrumentLabeledTicks1.Labels = instrumentTicksText2;
            elementSize21.Value = 0.15F;
            instrumentLabeledTicks1.Length = elementSize21;
            elementSize22.Value = 0.005F;
            instrumentLabeledTicks1.Thickness = elementSize22;
            instrumentLabeledTicks1.Visible = true;
            reversibleGaugeScale1.MinorTicks = instrumentLabeledTicks1;
            elementSize23.Value = 0.25F;
            reversibleGaugeScale1.Position = elementSize23;
            scalePrecision1.FixedPrecision = false;
            scalePrecision1.NumberDigits = ((uint)(2u));
            reversibleGaugeScale1.Precision = scalePrecision1;
            this.gaugeStbdTrim.Scale = reversibleGaugeScale1;
            this.gaugeStbdTrim.Size = new System.Drawing.Size(158, 424);
            this.gaugeStbdTrim.TabIndex = 0;
            this.gaugeStbdTrim.TabStop = false;
            this.gaugeStbdTrim.Text = "linearGauge1";
            this.gaugeStbdTrim.Value = 100D;
            // 
            // gaugePortTrim
            // 
            controlBackground2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.gaugePortTrim.Background = controlBackground2;
            controlInnerBevel2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlInnerBevel2.InternalData")));
            elementSize24.Value = 0.05F;
            controlInnerBevel2.Width = elementSize24;
            rectControlBorder2.BevelInner = controlInnerBevel2;
            elementSize25.Value = 0.05F;
            controlBevel2.Width = elementSize25;
            rectControlBorder2.BevelOuter = controlBevel2;
            rectControlBorder2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            elementSize26.Value = 0.2F;
            rectControlBorder2.CornerRadius = elementSize26;
            rectControlBorder2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("rectControlBorder2.InternalData")));
            elementSize27.Value = 0F;
            rectControlBorder2.Width = elementSize27;
            this.gaugePortTrim.Border = rectControlBorder2;
            verticalCaption2.Angle = 0F;
            gpBlend9.Blends = gpBlends9;
            gpBlendShape9.Focus = 0.5F;
            gpBlendShape9.Scale = 1F;
            gpBlend9.Shape = gpBlendShape9;
            gpBrush9.Blend = gpBlend9;
            gpBrush9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint9.X = 0F;
            gpCenterPoint9.Y = 0F;
            gpCenterColor9.Point = gpCenterPoint9;
            gpGradient9.CenterColor = gpCenterColor9;
            gpGradient9.Colors = gpColors9;
            gpGradient9.Path = gpPoints9;
            gpBrush9.Gradient = gpGradient9;
            gpHatch9.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch9.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush9.Hatch = gpHatch9;
            gpBrush9.InterpolationColors = gpInterpolationColors9;
            controlFont4.Brush = gpBrush9;
            controlFont4.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont4.InternalData")));
            gpBlend10.Blends = gpBlends10;
            gpBlendShape10.Focus = 0.5F;
            gpBlendShape10.Scale = 1F;
            gpBlend10.Shape = gpBlendShape10;
            gpBrush10.Blend = gpBlend10;
            gpBrush10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint10.X = 0F;
            gpCenterPoint10.Y = 0F;
            gpCenterColor10.Point = gpCenterPoint10;
            gpGradient10.CenterColor = gpCenterColor10;
            gpGradient10.Colors = gpColors10;
            gpGradient10.Path = gpPoints10;
            gpBrush10.Gradient = gpGradient10;
            gpHatch10.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch10.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush10.Hatch = gpHatch10;
            gpBrush10.InterpolationColors = gpInterpolationColors10;
            gpOptionalMultiPen4.Brush = gpBrush10;
            gpOptionalMultiPen4.Compound = gpPenCompound4;
            gpDashStyle4.CustomDash = gpCustomDash4;
            gpDashStyle4.Offset = 0F;
            gpOptionalMultiPen4.DashStyle = gpDashStyle4;
            gpOptionalMultiPen4.Enabled = false;
            gpOptionalMultiPen4.MiterLimit = 0F;
            gpOptionalMultiPen4.Width = 1F;
            controlFont4.Pen = gpOptionalMultiPen4;
            elementSize28.Value = 0.25F;
            controlFont4.Size = elementSize28;
            verticalCaption2.Font = controlFont4;
            elementOffsetSize5.Value = 0.8F;
            elementOffsets3.X = elementOffsetSize5;
            elementOffsetSize6.Value = 0F;
            elementOffsets3.Y = elementOffsetSize6;
            verticalCaption2.Position = elementOffsets3;
            this.gaugePortTrim.Caption = verticalCaption2;
            this.gaugePortTrim.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.gaugePortTrim.Curved = false;
            glass2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            glass2.Visible = false;
            this.gaugePortTrim.Glass = glass2;
            handAnimation2.Acceleration = 0.015F;
            handAnimation2.Resistance = 0.16F;
            optionalLinearGaugeHand2.Animation = handAnimation2;
            optionalLinearGaugeHand2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            elementSize29.Value = 0.33F;
            optionalLinearGaugeHand2.Length = elementSize29;
            optionalLinearGaugeHand2.Shadow = elementShadow2;
            elementSize30.Value = 0.15F;
            optionalLinearGaugeHand2.TailIndentSize = elementSize30;
            elementSize31.Value = 0.65F;
            optionalLinearGaugeHand2.TipLength = elementSize31;
            elementSize32.Value = 0.2F;
            optionalLinearGaugeHand2.TipWidth = elementSize32;
            elementSize33.Value = 0.03F;
            optionalLinearGaugeHand2.Width = elementSize33;
            this.gaugePortTrim.Hand = optionalLinearGaugeHand2;
            this.gaugePortTrim.InputPin = sinkPin2;
            this.gaugePortTrim.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("gaugePortTrim.InternalData")));
            this.gaugePortTrim.Location = new System.Drawing.Point(239, 44);
            this.gaugePortTrim.Max = 100D;
            this.gaugePortTrim.Min = 0D;
            this.gaugePortTrim.Name = "gaugePortTrim";
            elementSize34.Value = 0.9F;
            linearGaugeRail2.Length = elementSize34;
            elementOffsetSize7.Value = 0.1F;
            elementOffsets4.X = elementOffsetSize7;
            elementOffsetSize8.Value = 0F;
            elementOffsets4.Y = elementOffsetSize8;
            linearGaugeRail2.Position = elementOffsets4;
            elementSize35.Value = 0.08F;
            linearGaugeRail2.Width = elementSize35;
            this.gaugePortTrim.Rail = linearGaugeRail2;
            analogGaugeScaleRanges2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            elementSize36.Value = 0.2F;
            analogGaugeScaleRanges2.Position = elementSize36;
            elementSize37.Value = 0.05F;
            analogGaugeScaleRanges2.Width = elementSize37;
            this.gaugePortTrim.Ranges = analogGaugeScaleRanges2;
            rotation2.Angle = 180F;
            rotation2.Width = 0.7F;
            this.gaugePortTrim.Rotation = rotation2;
            gpBlend11.Blends = gpBlends11;
            gpBlendShape11.Focus = 0.5F;
            gpBlendShape11.Scale = 1F;
            gpBlend11.Shape = gpBlendShape11;
            gpBrush11.Blend = gpBlend11;
            gpBrush11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint11.X = 0F;
            gpCenterPoint11.Y = 0F;
            gpCenterColor11.Point = gpCenterPoint11;
            gpGradient11.CenterColor = gpCenterColor11;
            gpGradient11.Colors = gpColors11;
            gpGradient11.Path = gpPoints11;
            gpBrush11.Gradient = gpGradient11;
            gpHatch11.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch11.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush11.Hatch = gpHatch11;
            gpBrush11.InterpolationColors = gpInterpolationColors11;
            instrumentMajorTicks2.Brush = gpBrush11;
            instrumentMajorTicks2.Count = ((uint)(5u));
            instrumentTicksText3.Angle = 0F;
            gpBlend12.Blends = gpBlends12;
            gpBlendShape12.Focus = 0.5F;
            gpBlendShape12.Scale = 1F;
            gpBlend12.Shape = gpBlendShape12;
            gpBrush12.Blend = gpBlend12;
            gpBrush12.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor12.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint12.X = 0F;
            gpCenterPoint12.Y = 0F;
            gpCenterColor12.Point = gpCenterPoint12;
            gpGradient12.CenterColor = gpCenterColor12;
            gpGradient12.Colors = gpColors12;
            gpGradient12.Path = gpPoints12;
            gpBrush12.Gradient = gpGradient12;
            gpHatch12.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch12.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush12.Hatch = gpHatch12;
            gpBrush12.InterpolationColors = gpInterpolationColors12;
            controlFont5.Brush = gpBrush12;
            controlFont5.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont5.InternalData")));
            gpBlend13.Blends = gpBlends13;
            gpBlendShape13.Focus = 0.5F;
            gpBlendShape13.Scale = 1F;
            gpBlend13.Shape = gpBlendShape13;
            gpBrush13.Blend = gpBlend13;
            gpBrush13.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor13.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint13.X = 0F;
            gpCenterPoint13.Y = 0F;
            gpCenterColor13.Point = gpCenterPoint13;
            gpGradient13.CenterColor = gpCenterColor13;
            gpGradient13.Colors = gpColors13;
            gpGradient13.Path = gpPoints13;
            gpBrush13.Gradient = gpGradient13;
            gpHatch13.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch13.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush13.Hatch = gpHatch13;
            gpBrush13.InterpolationColors = gpInterpolationColors13;
            gpOptionalMultiPen5.Brush = gpBrush13;
            gpOptionalMultiPen5.Compound = gpPenCompound5;
            gpDashStyle5.CustomDash = gpCustomDash5;
            gpDashStyle5.Offset = 0F;
            gpOptionalMultiPen5.DashStyle = gpDashStyle5;
            gpOptionalMultiPen5.Enabled = false;
            gpOptionalMultiPen5.MiterLimit = 0F;
            gpOptionalMultiPen5.Width = 1F;
            controlFont5.Pen = gpOptionalMultiPen5;
            elementSize38.Value = 0.09F;
            controlFont5.Size = elementSize38;
            instrumentTicksText3.Font = controlFont5;
            elementSize39.Value = 0.5F;
            instrumentTicksText3.Position = elementSize39;
            instrumentTicksText3.Visible = true;
            instrumentMajorTicks2.Labels = instrumentTicksText3;
            elementSize40.Value = 0.25F;
            instrumentMajorTicks2.Length = elementSize40;
            optionalInstrumentProperty3.Visible = true;
            instrumentEndTick3.TickLabel = optionalInstrumentProperty3;
            instrumentEndTick3.Visible = true;
            instrumentMajorTicks2.MaxTick = instrumentEndTick3;
            optionalInstrumentProperty4.Visible = true;
            instrumentEndTick4.TickLabel = optionalInstrumentProperty4;
            instrumentEndTick4.Visible = true;
            instrumentMajorTicks2.MinTick = instrumentEndTick4;
            elementSize41.Value = 0.01F;
            instrumentMajorTicks2.Thickness = elementSize41;
            instrumentMajorTicks2.Visible = true;
            reversibleGaugeScale2.MajorTicks = instrumentMajorTicks2;
            gpBlend14.Blends = gpBlends14;
            gpBlendShape14.Focus = 0.5F;
            gpBlendShape14.Scale = 1F;
            gpBlend14.Shape = gpBlendShape14;
            gpBrush14.Blend = gpBlend14;
            gpBrush14.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterColor14.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint14.X = 0F;
            gpCenterPoint14.Y = 0F;
            gpCenterColor14.Point = gpCenterPoint14;
            gpGradient14.CenterColor = gpCenterColor14;
            gpGradient14.Colors = gpColors14;
            gpGradient14.Path = gpPoints14;
            gpBrush14.Gradient = gpGradient14;
            gpHatch14.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch14.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush14.Hatch = gpHatch14;
            gpBrush14.InterpolationColors = gpInterpolationColors14;
            instrumentLabeledTicks2.Brush = gpBrush14;
            instrumentLabeledTicks2.Count = ((uint)(3u));
            instrumentTicksText4.Angle = 0F;
            gpBlend15.Blends = gpBlends15;
            gpBlendShape15.Focus = 0.5F;
            gpBlendShape15.Scale = 1F;
            gpBlend15.Shape = gpBlendShape15;
            gpBrush15.Blend = gpBlend15;
            gpBrush15.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor15.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint15.X = 0F;
            gpCenterPoint15.Y = 0F;
            gpCenterColor15.Point = gpCenterPoint15;
            gpGradient15.CenterColor = gpCenterColor15;
            gpGradient15.Colors = gpColors15;
            gpGradient15.Path = gpPoints15;
            gpBrush15.Gradient = gpGradient15;
            gpHatch15.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch15.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush15.Hatch = gpHatch15;
            gpBrush15.InterpolationColors = gpInterpolationColors15;
            controlFont6.Brush = gpBrush15;
            controlFont6.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("controlFont6.InternalData")));
            gpBlend16.Blends = gpBlends16;
            gpBlendShape16.Focus = 0.5F;
            gpBlendShape16.Scale = 1F;
            gpBlend16.Shape = gpBlendShape16;
            gpBrush16.Blend = gpBlend16;
            gpBrush16.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpCenterColor16.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpCenterPoint16.X = 0F;
            gpCenterPoint16.Y = 0F;
            gpCenterColor16.Point = gpCenterPoint16;
            gpGradient16.CenterColor = gpCenterColor16;
            gpGradient16.Colors = gpColors16;
            gpGradient16.Path = gpPoints16;
            gpBrush16.Gradient = gpGradient16;
            gpHatch16.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            gpHatch16.ForegroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            gpBrush16.Hatch = gpHatch16;
            gpBrush16.InterpolationColors = gpInterpolationColors16;
            gpOptionalMultiPen6.Brush = gpBrush16;
            gpOptionalMultiPen6.Compound = gpPenCompound6;
            gpDashStyle6.CustomDash = gpCustomDash6;
            gpDashStyle6.Offset = 0F;
            gpOptionalMultiPen6.DashStyle = gpDashStyle6;
            gpOptionalMultiPen6.Enabled = false;
            gpOptionalMultiPen6.MiterLimit = 0F;
            gpOptionalMultiPen6.Width = 1F;
            controlFont6.Pen = gpOptionalMultiPen6;
            elementSize42.Value = 0.065F;
            controlFont6.Size = elementSize42;
            instrumentTicksText4.Font = controlFont6;
            elementSize43.Value = 0.45F;
            instrumentTicksText4.Position = elementSize43;
            instrumentTicksText4.Visible = false;
            instrumentLabeledTicks2.Labels = instrumentTicksText4;
            elementSize44.Value = 0.15F;
            instrumentLabeledTicks2.Length = elementSize44;
            elementSize45.Value = 0.005F;
            instrumentLabeledTicks2.Thickness = elementSize45;
            instrumentLabeledTicks2.Visible = true;
            reversibleGaugeScale2.MinorTicks = instrumentLabeledTicks2;
            elementSize46.Value = 0.25F;
            reversibleGaugeScale2.Position = elementSize46;
            scalePrecision2.FixedPrecision = false;
            scalePrecision2.NumberDigits = ((uint)(2u));
            reversibleGaugeScale2.Precision = scalePrecision2;
            reversibleGaugeScale2.Reversed = true;
            this.gaugePortTrim.Scale = reversibleGaugeScale2;
            this.gaugePortTrim.Size = new System.Drawing.Size(158, 424);
            this.gaugePortTrim.TabIndex = 108;
            this.gaugePortTrim.TabStop = false;
            this.gaugePortTrim.Text = "linearGauge2";
            this.gaugePortTrim.Value = 100D;
            // 
            // label36
            // 
            this.label36.Font = new System.Drawing.Font("Arial", 14F);
            this.label36.ForeColor = System.Drawing.Color.White;
            this.label36.Location = new System.Drawing.Point(168, 6);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(479, 25);
            this.label36.TabIndex = 109;
            this.label36.Text = "TRIM CONTROL";
            this.label36.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Arial", 14F);
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(19, 91);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(199, 25);
            this.label1.TabIndex = 110;
            this.label1.Text = "PORT";
            this.label1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label2
            // 
            this.label2.Font = new System.Drawing.Font("Arial", 14F);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(582, 91);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(199, 25);
            this.label2.TabIndex = 111;
            this.label2.Text = "STBD";
            this.label2.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            // 
            // label5
            // 
            this.label5.Font = new System.Drawing.Font("Arial", 36F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(264, 232);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(102, 46);
            this.label5.TabIndex = 112;
            this.label5.Text = "--";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label3
            // 
            this.label3.Font = new System.Drawing.Font("Arial", 36F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(436, 232);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(102, 46);
            this.label3.TabIndex = 113;
            this.label3.Text = "--";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Black;
            this.panel1.Location = new System.Drawing.Point(262, 75);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(31, 360);
            this.panel1.TabIndex = 114;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.Black;
            this.panel2.Location = new System.Drawing.Point(513, 77);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(33, 360);
            this.panel2.TabIndex = 115;
            // 
            // label4
            // 
            this.label4.BackColor = System.Drawing.Color.Black;
            this.label4.Font = new System.Drawing.Font("Arial", 14F);
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(257, 420);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(70, 25);
            this.label4.TabIndex = 116;
            this.label4.Text = "100%";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label6
            // 
            this.label6.BackColor = System.Drawing.Color.Black;
            this.label6.Font = new System.Drawing.Font("Arial", 14F);
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(273, 243);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(54, 25);
            this.label6.TabIndex = 117;
            this.label6.Text = "50%";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label7
            // 
            this.label7.BackColor = System.Drawing.Color.Black;
            this.label7.Font = new System.Drawing.Font("Arial", 14F);
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(273, 154);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(54, 25);
            this.label7.TabIndex = 118;
            this.label7.Text = "25%";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label8
            // 
            this.label8.BackColor = System.Drawing.Color.Black;
            this.label8.Font = new System.Drawing.Font("Arial", 14F);
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(273, 331);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(54, 25);
            this.label8.TabIndex = 119;
            this.label8.Text = "75%";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label9
            // 
            this.label9.BackColor = System.Drawing.Color.Black;
            this.label9.Font = new System.Drawing.Font("Arial", 14F);
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(273, 66);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(54, 25);
            this.label9.TabIndex = 120;
            this.label9.Text = "0%";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label10
            // 
            this.label10.BackColor = System.Drawing.Color.Black;
            this.label10.Font = new System.Drawing.Font("Arial", 14F);
            this.label10.ForeColor = System.Drawing.Color.White;
            this.label10.Location = new System.Drawing.Point(480, 67);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(54, 25);
            this.label10.TabIndex = 125;
            this.label10.Text = "0%";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label11
            // 
            this.label11.BackColor = System.Drawing.Color.Black;
            this.label11.Font = new System.Drawing.Font("Arial", 14F);
            this.label11.ForeColor = System.Drawing.Color.White;
            this.label11.Location = new System.Drawing.Point(480, 332);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(54, 25);
            this.label11.TabIndex = 124;
            this.label11.Text = "75%";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label12
            // 
            this.label12.BackColor = System.Drawing.Color.Black;
            this.label12.Font = new System.Drawing.Font("Arial", 14F);
            this.label12.ForeColor = System.Drawing.Color.White;
            this.label12.Location = new System.Drawing.Point(480, 155);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(54, 25);
            this.label12.TabIndex = 123;
            this.label12.Text = "25%";
            this.label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label13
            // 
            this.label13.BackColor = System.Drawing.Color.Black;
            this.label13.Font = new System.Drawing.Font("Arial", 14F);
            this.label13.ForeColor = System.Drawing.Color.White;
            this.label13.Location = new System.Drawing.Point(480, 244);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(54, 25);
            this.label13.TabIndex = 122;
            this.label13.Text = "50%";
            this.label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label14
            // 
            this.label14.BackColor = System.Drawing.Color.Black;
            this.label14.Font = new System.Drawing.Font("Arial", 14F);
            this.label14.ForeColor = System.Drawing.Color.White;
            this.label14.Location = new System.Drawing.Point(480, 421);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(70, 25);
            this.label14.TabIndex = 121;
            this.label14.Text = "100%";
            this.label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // checkBox1
            // 
            this.checkBox1.AutoSize = true;
            this.checkBox1.Checked = true;
            this.checkBox1.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox1.Font = new System.Drawing.Font("Arial", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.checkBox1.ForeColor = System.Drawing.Color.White;
            this.checkBox1.Location = new System.Drawing.Point(604, 23);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(167, 26);
            this.checkBox1.TabIndex = 127;
            this.checkBox1.Text = "SYNCHRONIZE";
            this.checkBox1.UseVisualStyleBackColor = true;
            // 
            // dashboardButton2
            // 
            this.dashboardButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton2.BackgroundImage")));
            this.dashboardButton2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.dashboardButton2.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.dashboardButton2.FlatAppearance.BorderSize = 0;
            this.dashboardButton2.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton2.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dashboardButton2.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardButton2.ForeColor = System.Drawing.Color.White;
            this.dashboardButton2.Function = "PORT TRIM DOWN";
            this.dashboardButton2.Location = new System.Drawing.Point(19, 248);
            this.dashboardButton2.MvecAddress = ((byte)(177));
            this.dashboardButton2.MvecFuseNumber = ((byte)(8));
            this.dashboardButton2.MvecGrid = ((byte)(0));
            this.dashboardButton2.MvecRelayNumber = ((byte)(5));
            this.dashboardButton2.Name = "dashboardButton2";
            this.dashboardButton2.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton2.OffStateBackImage")));
            this.dashboardButton2.OffStateForeColor = System.Drawing.Color.White;
            this.dashboardButton2.OffStateText = "BOW\r\nDOWN";
            this.dashboardButton2.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton2.OnStateBackImage")));
            this.dashboardButton2.OnStateForeColor = System.Drawing.Color.White;
            this.dashboardButton2.OnStateText = "BOW\r\nDOWN";
            this.dashboardButton2.Size = new System.Drawing.Size(199, 111);
            this.dashboardButton2.State = false;
            this.dashboardButton2.TabIndex = 107;
            this.dashboardButton2.Text = "BOW\r\nDOWN";
            this.dashboardButton2.UseVisualStyleBackColor = true;
            this.dashboardButton2.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.dashboardButton2_NewCommand);
            // 
            // dashboardButton3
            // 
            this.dashboardButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton3.BackgroundImage")));
            this.dashboardButton3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.dashboardButton3.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.dashboardButton3.FlatAppearance.BorderSize = 0;
            this.dashboardButton3.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton3.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dashboardButton3.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardButton3.ForeColor = System.Drawing.Color.White;
            this.dashboardButton3.Function = "PORT TRIM UP";
            this.dashboardButton3.Location = new System.Drawing.Point(19, 131);
            this.dashboardButton3.MvecAddress = ((byte)(177));
            this.dashboardButton3.MvecFuseNumber = ((byte)(4));
            this.dashboardButton3.MvecGrid = ((byte)(0));
            this.dashboardButton3.MvecRelayNumber = ((byte)(2));
            this.dashboardButton3.Name = "dashboardButton3";
            this.dashboardButton3.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton3.OffStateBackImage")));
            this.dashboardButton3.OffStateForeColor = System.Drawing.Color.White;
            this.dashboardButton3.OffStateText = "BOW\r\nUP";
            this.dashboardButton3.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton3.OnStateBackImage")));
            this.dashboardButton3.OnStateForeColor = System.Drawing.Color.White;
            this.dashboardButton3.OnStateText = "BOW\r\nUP";
            this.dashboardButton3.Size = new System.Drawing.Size(199, 111);
            this.dashboardButton3.State = false;
            this.dashboardButton3.TabIndex = 106;
            this.dashboardButton3.Text = "BOW\r\nUP";
            this.dashboardButton3.UseVisualStyleBackColor = true;
            this.dashboardButton3.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.dashboardButton3_NewCommand);
            this.dashboardButton3.Click += new System.EventHandler(this.dashboardButton3_Click);
            // 
            // dashboardButton1
            // 
            this.dashboardButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton1.BackgroundImage")));
            this.dashboardButton1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.dashboardButton1.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.dashboardButton1.FlatAppearance.BorderSize = 0;
            this.dashboardButton1.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dashboardButton1.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardButton1.ForeColor = System.Drawing.Color.White;
            this.dashboardButton1.Function = "STBD TRIM DOWN";
            this.dashboardButton1.Location = new System.Drawing.Point(582, 248);
            this.dashboardButton1.MvecAddress = ((byte)(177));
            this.dashboardButton1.MvecFuseNumber = ((byte)(2));
            this.dashboardButton1.MvecGrid = ((byte)(0));
            this.dashboardButton1.MvecRelayNumber = ((byte)(4));
            this.dashboardButton1.Name = "dashboardButton1";
            this.dashboardButton1.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton1.OffStateBackImage")));
            this.dashboardButton1.OffStateForeColor = System.Drawing.Color.White;
            this.dashboardButton1.OffStateText = "BOW\r\nDOWN";
            this.dashboardButton1.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton1.OnStateBackImage")));
            this.dashboardButton1.OnStateForeColor = System.Drawing.Color.White;
            this.dashboardButton1.OnStateText = "BOW\r\nDOWN";
            this.dashboardButton1.Size = new System.Drawing.Size(199, 111);
            this.dashboardButton1.State = false;
            this.dashboardButton1.TabIndex = 105;
            this.dashboardButton1.Text = "BOW\r\nDOWN";
            this.dashboardButton1.UseVisualStyleBackColor = true;
            this.dashboardButton1.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.dashboardButton1_NewCommand);
            // 
            // dashboardButton7
            // 
            this.dashboardButton7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton7.BackgroundImage")));
            this.dashboardButton7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.dashboardButton7.ButtonBehavior = BoatFormsLib.CustomUserControls.ButtonBehavior.Momentary;
            this.dashboardButton7.FlatAppearance.BorderSize = 0;
            this.dashboardButton7.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton7.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.dashboardButton7.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dashboardButton7.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardButton7.ForeColor = System.Drawing.Color.White;
            this.dashboardButton7.Function = "STBD TRIM UP";
            this.dashboardButton7.Location = new System.Drawing.Point(582, 131);
            this.dashboardButton7.MvecAddress = ((byte)(177));
            this.dashboardButton7.MvecFuseNumber = ((byte)(1));
            this.dashboardButton7.MvecGrid = ((byte)(0));
            this.dashboardButton7.MvecRelayNumber = ((byte)(1));
            this.dashboardButton7.Name = "dashboardButton7";
            this.dashboardButton7.OffStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton7.OffStateBackImage")));
            this.dashboardButton7.OffStateForeColor = System.Drawing.Color.White;
            this.dashboardButton7.OffStateText = "BOW\r\nUP";
            this.dashboardButton7.OnStateBackImage = ((System.Drawing.Image)(resources.GetObject("dashboardButton7.OnStateBackImage")));
            this.dashboardButton7.OnStateForeColor = System.Drawing.Color.White;
            this.dashboardButton7.OnStateText = "BOW\r\nUP";
            this.dashboardButton7.Size = new System.Drawing.Size(199, 111);
            this.dashboardButton7.State = false;
            this.dashboardButton7.TabIndex = 104;
            this.dashboardButton7.Text = "BOW\r\nUP";
            this.dashboardButton7.UseVisualStyleBackColor = true;
            this.dashboardButton7.NewCommand += new System.EventHandler<BoatFormsLib.DashboardButtonArgs>(this.dashboardButton7_NewCommand);
            // 
            // TrimControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(44)))), ((int)(((byte)(51)))));
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.Controls.Add(this.checkBox1);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.gaugePortTrim);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label36);
            this.Controls.Add(this.dashboardButton2);
            this.Controls.Add(this.dashboardButton3);
            this.Controls.Add(this.dashboardButton1);
            this.Controls.Add(this.dashboardButton7);
            this.Controls.Add(this.gaugeStbdTrim);
            this.Controls.Add(this.label3);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "TrimControl";
            this.Text = "TrimControl";
            ((System.ComponentModel.ISupportInitialize)(this.gaugeStbdTrim)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gaugePortTrim)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Mitov.InstrumentLab.LinearGauge gaugeStbdTrim;
        private BoatFormsLib.CustomUserControls.DashboardButton dashboardButton7;
        private BoatFormsLib.CustomUserControls.DashboardButton dashboardButton1;
        private BoatFormsLib.CustomUserControls.DashboardButton dashboardButton2;
        private BoatFormsLib.CustomUserControls.DashboardButton dashboardButton3;
        private Mitov.InstrumentLab.LinearGauge gaugePortTrim;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.CheckBox checkBox1;
    }
}